### ISSUE TITLE
Use a fixed and generic entrypoint for model.yaml/RDF in a package

### ISSUE THREAD

**Issue by oeway** [bioimage-io/archive.bioimage.io#106]
This issue is brought up in https://github.com/bioimage-io/bioimage.io/pull/104, lets continue the discussion here:

@oeway  wrote:

> We had some discussion a while about when we place the model yaml inside a package, we should rename it to model.yaml. The thing is we will need some kind of fixed entrypoint (a bit like the setup.py file of a python package and index.html page of a website), otherwise we will need to search within the package which is not always possible (e.g. on zenodo it will generate more requests). Plus, we don't want really multiple yaml in one package.

> And now while working on other RDF file, I am even thinking we should perhaps rename model.yaml to something more generic, so we can also pacakge datasets, notebooks, applications, and share the same entry point yaml file name. I thought about config.yaml but then noticed it might be confusing since we have config key in the model.yaml. I would propose something like rdf.yaml, rdf.bioimage.io.yaml, or bioimage.io.yaml.

@constantinpape wrote:
> I agree, we should update this so we have a unified entry point.
I suggest we discuss this in a separate issue in the spec repo.

**Comment by constantinpape** [comment]
> I would propose something like rdf.yaml, rdf.bioimage.io.yaml, or bioimage.io.yaml.

Would all be fine with me.

**Comment by oeway** [comment]
This is now implemented as `rdf.yaml`.
