### ISSUE TITLE
missing caps i on landing page

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#110]
Accoring to https://github.com/bioimage-io/bioimage.io/issues/28#issuecomment-802927010 is should be BioImage I think.... 
![image](https://user-images.githubusercontent.com/15139589/122192287-cffe5c80-ce93-11eb-8125-fc308f81ed4f.png)

Right there in front of our eyes... 👀

**Comment by oeway** [comment]
Nice catch! Will do!
