### ISSUE TITLE
Are models downloadable as zip archives from zenodo?

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#111]
Hello @oeway,

quick question: I wanted to try one of the modelzoo compliant networks @constantinpape has trained, brought up to spec and uploaded it (via the bioimageio uploader as it says on zenodo): [model](https://sandbox.zenodo.org/record/865618#.YMnEoCWxVpQ).

I'm not sure I've overlooked it, but it seems that all files have to be downloaded separately? Or is the a secret download all button somewhere?

Cheers

**Comment by esgomezm** [comment]
Hi @oeway , @constantinpape and @k-dominik 

Thank you for working on this these days. I also think that having the download link is one of the most important things for the course. For zenodo sandbox it’s also fine. 

Do you expect the participants to upload models during the course? Or just interact with the existing ones?

**Comment by constantinpape** [comment]
> Do you expect the participants to upload models during the course? Or just interact with the existing ones?

For now, we are training and uploading some models and I think it's good if participants can easily download them via the packager.
I am not sure what other plans @akreshuk or @k-dominik have and if that involves participants uploading models.

**Comment by akreshuk** [comment]
No, no upload, I think we have our hands full as it is :)

**Comment by oeway** [comment]
You may wonder why it's closed, I have implemented the link so now you can click the download package link from zenodo and it will bring you to the bioimageio model page.

**Comment by esgomezm** [comment]
Ok! Yes, I also think it's better to not start uploading any kind of model.
