### ISSUE TITLE
Issues with upload functionality

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#113]
Remaining issues with upload functionality; collecting these here to keep track of it after merging #104.

## Upload does not work on Ubuntu + Firefox combination

See https://github.com/bioimage-io/bioimage.io/pull/104#issuecomment-851531923 for details.
Note that this so far only occured on my laptop it works fine for me with different linux systems.

## Upload does not work with chromium + Linux

See https://github.com/bioimage-io/bioimage.io/pull/104#issuecomment-861807633 for details
I can reproduce this on two different linux machines.

**Comment by oeway** [comment]
@constantinpape I just checked the [second issue](https://github.com/bioimage-io/bioimage.io/pull/104#issuecomment-861807633) you described above, the reason for that to close is the timeout value was set to 20s. I can just set a longer timeout e.g. 60s.

**Comment by constantinpape** [comment]
> @constantinpape I just checked the [second issue](https://github.com/bioimage-io/bioimage.io/pull/104#issuecomment-861807633) you described above, the reason for that to close is the timeout value was set to 20s. I can just set a longer timeout e.g. 60s.

Ok, that would be good. I would set something > 2 min, given that some users may need to wait for 2FA.

**Comment by oeway** [comment]
> > @constantinpape I just checked the [second issue](https://github.com/bioimage-io/bioimage.io/pull/104#issuecomment-861807633) you described above, the reason for that to close is the timeout value was set to 20s. I can just set a longer timeout e.g. 60s.
> 
> 
> 
> Ok, that would be good. I would set something > 2 min, given that some users may need to wait for 2FA.

Done, now it's 120s in the PR #117, please test it out and see how it works.

**Comment by constantinpape** [comment]
> Done, now it's 120s in the PR #117, please test it out and see how it works.

Yes, already tested it and works well now.

**Comment by constantinpape** [comment]
Just btw, https://github.com/bioimage-io/bioimage.io/pull/104#issuecomment-851531923 was indeed an issue with pop-ups being blocked, I just didn't realized this was so hidden since the latest firefox upgrades. Having the warning button that indicates that pop-ups are blocked helps a lot to spot this now.
