### ISSUE TITLE
Upload functionality stopped working

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#116]
The upload functionality stopped working for me (Centos 8, Firefox 78.11):
After clicking "Authorize Application" on zenodo, a blank page with thext "Forwarding data to the main window..." appears, but the window on bioimage.io is not being updated.

**Comment by oeway** [comment]
I can reproduce this issue on mac with FireFox for the first time, but it behaves normal afterwards. Could you try it a second time?
