### ISSUE TITLE
How to update a model via upload button?

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#118]
I am trying to update a model via the update button, however I am only shown that a nameclash exist, but not able to go forward to update the model with that name:

![Screenshot from 2021-06-20 19-59-59](https://user-images.githubusercontent.com/4263537/122683871-530c1380-d202-11eb-9098-c083dabde662.png)

**Comment by oeway** [comment]
What do you want to do exactly? This means you need to rename your current local model by clicking "go back to rename". 

Do you mean you want to overwrite the package on zenodo? If yes. Could you try to specify the doi of your existing model in the first step use option 3, then try to update it.


We don't support updating deposits with a package (option 1) for now, perhaps we should also support that, e.g. add a "Update" button on the detected deposit.

**Comment by constantinpape** [comment]
> Do you mean you want to overwrite the package on zenodo?

Yes, exactly.

> Could you try to specify the doi of your existing model in the first step use option 3, then try to update it.

I tried that for this model: https://sandbox.zenodo.org/record/865994#.YM-RsTqxXJU
But I run into the folloing error:
![Screenshot from 2021-06-20 21-09-55](https://user-images.githubusercontent.com/4263537/122685491-f877b500-d20b-11eb-8823-8cf98b95a7c5.png)


> We don't support updating deposits with a package (option 1) for now, perhaps we should also support that, e.g. add a "Update" button on the detected deposit.

Yes, I think it would be good to support this option, it's easier than searching for the doi before updating.

**Comment by oeway** [comment]
@constantinpape Could you give it a try: https://github.com/bioimage-io/bioimage.io/pull/119/

I fixed both options.
