### ISSUE TITLE
model upload throws error :/

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#128]
Hello @oeway,

I was trying to upload some networks that @constantinpape kindly provided (really just minor upgrades, but need to re-upload as I don't have access to his account). In any case, when I add the file and press on "upload as new deposit" i get the following error:

![upload-error](https://user-images.githubusercontent.com/24434157/123671656-cf27dc00-d83e-11eb-9b9a-d9b2680d05b1.png)

is there any way I can provide you with additional information?
Cheers
Dominik

p.s.: [link to model file](https://oc.embl.de/index.php/s/Ft5zeex4TWogJix)

**Comment by oeway** [comment]
Hi, thanks for the report, could you also paste the error log by open the browser console?

**Comment by k-dominik** [comment]
not sure it's much of a help, but here's the content of the error log:

<details>

```js
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data app.34a8c6f2.js:1
    i app.34a8c6f2.js:1
    l chunk-vendors.470b33a2.js:50322
    I chunk-vendors.470b33a2.js:50322
    t chunk-vendors.470b33a2.js:50322
    n chunk-vendors.470b33a2.js:1
    c chunk-vendors.470b33a2.js:1
    (Async: promise callback)
    n chunk-vendors.470b33a2.js:1
    s chunk-vendors.470b33a2.js:1
    (Async: promise callback)
    n chunk-vendors.470b33a2.js:1
    s chunk-vendors.470b33a2.js:1
    o chunk-vendors.470b33a2.js:1
    o chunk-vendors.470b33a2.js:1
    createOrUpdateDeposit app.34a8c6f2.js:1
    click app.34a8c6f2.js:1
    it chunk-vendors.470b33a2.js:26905
    i chunk-vendors.470b33a2.js:26905
    _wrapper chunk-vendors.470b33a2.js:26905
    (Async: EventListener.handleEvent)
    Jo chunk-vendors.470b33a2.js:26905
    vt chunk-vendors.470b33a2.js:26905
    tr chunk-vendors.470b33a2.js:26905
    T chunk-vendors.470b33a2.js:26905
    f chunk-vendors.470b33a2.js:26905
    Do chunk-vendors.470b33a2.js:26905
    _update chunk-vendors.470b33a2.js:26905
    n chunk-vendors.470b33a2.js:26905
    get chunk-vendors.470b33a2.js:26905
    tn chunk-vendors.470b33a2.js:26905
    ki chunk-vendors.470b33a2.js:26905
    $mount chunk-vendors.470b33a2.js:26905
    init chunk-vendors.470b33a2.js:26905
    m chunk-vendors.470b33a2.js:26905
    f chunk-vendors.470b33a2.js:26905
    E chunk-vendors.470b33a2.js:26905
    f chunk-vendors.470b33a2.js:26905
    L chunk-vendors.470b33a2.js:26905
    C chunk-vendors.470b33a2.js:26905
    L chunk-vendors.470b33a2.js:26905
```

</details>

does it work for you with the provided model?

**Comment by oeway** [comment]
With the details you provided, I can locate roughly where the error is from, however, I tried to upload the same file without an y issue.

See here: https://sandbox.zenodo.org/record/872710

**Comment by k-dominik** [comment]
hmm so I changed the name of the model and also bumped the version to 0.1.1 ... might this be the cause? I'll try a different browser...

**Comment by k-dominik** [comment]
ah, sorry, it was a me issue. I didn't get a verification email from zenodo.. Once I re-requested it and verified  the account it was all nice

**Comment by oeway** [comment]
> ah, sorry, it was a me issue. I didn't get a verification email from zenodo.. Once I re-requested it and verified the account it was all nice

Could you elaborate what you did? You registered a new account, and it brings you back to bioimage.io, it might be better we warn the user about that.

BTW, I just removed the 3 ISBI2012-2D-BoundaryModel models (2 by constantin and 1 by me) from the bioimage.io collection, if understand correctly, you will upload a new corrected one, right?

**Comment by k-dominik** [comment]
> Could you elaborate what you did? You registered a new account, and it brings you back to bioimage.io, it might be better we warn the user about that.

I registered a new account (by going to sandbox.zenode... directly). Then I didn't get a confirmation email, but I already tried uploading a model via bioimageio. That resulted in the error.



> BTW, I just removed the 3 ISBI2012-2D-BoundaryModel models (2 by constantin and 1 by me) from the bioimage.io collection, if understand correctly, you will upload a new corrected one, right?

I'll upload five models:

* `CREMI-BoundaryModel`
* `DSB-Nuclei-BoundaryModel`
* `ISBI2012-2D-BoundaryModel`
* `Platyereis-cells-BoundaryModel`
* `Platyereis-nuclei-BoundaryModel`

so it would be cool if you could remove the predecessors to these

**Comment by k-dominik** [comment]
great that you have addressed that @oeway,
in addition to the above models, could you also please remove
* 2D UNet Arabitopsis Ovules
* 3D UNet Arabidopsis Ovules
* 3D UNet Lateral Root Primordia Nuclei
* 3D UNet Lateral Root Primordia Cell Boundaries

**Comment by k-dominik** [comment]
I guess the old ones we have under our control, right? Should we just empty our manifest and upload everything?

**Comment by oeway** [comment]
> great that you have addressed that @oeway,
> in addition to the above models, could you also please remove
> 
> * 2D UNet Arabitopsis Ovules
> * 3D UNet Arabidopsis Ovules
> * 3D UNet Lateral Root Primordia Nuclei
> * 3D UNet Lateral Root Primordia Cell Boundaries

@k-dominik It appears that all these models are coming from github (not zenodo ), you can tell that from whether it has a zenodo doi badge. In order to remove those, you just need to remove those entries from the manifest.bioimage.io.yaml file in the ilastik model repo. And our CI will pick it up in 2h maximum, or you can manually trigger the CI to run in this repo: https://github.com/bioimage-io/bioimage-io-models

> I guess the old ones we have under our control, right? Should we just empty our manifest and upload everything?

Yes, feel free to do that, however, please also keep in mind that we are using sandbox mode of zenodo at this stage, we will support publishing models to the production zenodo when we fully tested it. Well it would actually good if you can try to upload as many models as you have to fully test the upload feature and the presentation of the models, that's the only way to fully test it and make it production ready.
