### ISSUE TITLE
Logo for bioimage.io

### ISSUE THREAD

**Issue by oeway** [bioimage-io/archive.bioimage.io#13]
Hi, we need a logo for bioimage.io, any idea?

**Comment by MartinHjelmare** [comment]
1. A stylized cell chopped up into four puzzle pieces.

PS. Please continue the numbered list when making suggestions.

**Comment by MartinHjelmare** [comment]
For reference, it can be helpful to look at the image.sc forum to see what's out there already:
https://forum.image.sc/

**Comment by oeway** [comment]
2. several zoo animals (giraffe etc.) plotted with edges and nodes like neural networks.

Here goes a densely connected network:
<img width="200" alt="Screenshot 2020-03-07 at 12 33 50" src="https://user-images.githubusercontent.com/478667/76142645-ece09900-606f-11ea-8a6b-8931eaf92e54.png">

**Comment by constantinpape** [comment]
>     1. several zoo animals (giraffe etc.) plotted with edges and nodes like neural networks.
> 
> 
> Here goes a densely connected network:

Great idea!
