### ISSUE TITLE
Zipping by model packager is very slow

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#145]
Making the zip with the model packager still takes very long, esp. for large models, e.g. https://bioimage.io/#/?id=10.5072%2Fzenodo.880412.
For this one, making the zip took more than 5 minutes.
In comparison using gzip locally took maybe 10 seconds.

This is a big problem in usability, as a user I don't want to wait 5 minutes before the download even starts.

@oeway why is the difference in runtume so significant? What library are you using for zipping?
Can we compile gzip / zlib with wasm and use it in the packager?

**Comment by constantinpape** [comment]
Potentially useful: https://github.com/emscripten-ports/zlib

**Comment by oeway** [comment]
I used jsZip which is pure js implementation. I just tried the same sample as you did and it took 3 minutes in chrome to make the zip file which is still too slow.

**Comment by constantinpape** [comment]
> I used jsZip which is pure js implementation.

Yeah, I think we need to use something more optimized here.

I could have a look in doing this via wasm (maybe we could just use the port from emscripten), but it would maybe be good to have a short zoom to discuss how to pipe that into the packager.

**Comment by oeway** [comment]
There is also another light weight alternative: https://github.com/photopea/UZIP.js which I haven't tried yet.

> I could have a look in doing this via wasm (maybe we could just use the port from emscripten), but it would maybe be good to have a short zoom to discuss how to pipe that into the packager.

WASM would be a good choice, but I think there must be implementations compiled by others out there. We should look into those before work on it I think.

I just tried WasmZip, they have a demo here: https://bpajk.github.io/WasmZip/  Your torch script model files took 1min45s for me, ( and it takes 3 minutes in JsZip) -- not so significant improvements, but certainly faster. We might also be able to play with the compression ratio.

EDIT: it's not a fair comparison because the WasmZip case includes time for reading content from disk (which can take some time for large files), so if we use it for the packager, it should be faster.

**Comment by constantinpape** [comment]
> WASM would be a good choice, but I think there must be implementations compiled by others out there. We should look into those before work on it I think.

Sounds good; ofc much better if we can use something existing already.

It would be great if we could get to < 30s for the mito-em model

**Comment by oeway** [comment]
> It would be great if we could get to < 30s for the mito-em model

I just [released a version](https://github.com/imjoy-team/bioimage-io-models/commit/12356841f67097eab979d09087af627be002d847) that uses UZIP.js which takes 29.774s (<30s!!!) to compress your files ;)

Please give it (the general packager, not the ilastik one) a try! @constantinpape  If you open the console, it will print how much time does it take for downloading and zipping.

Did not use the WASM implementation, the intuition is that the files are already downloaded to the browser, compression is not that important. So I didn't not use any compression, the files are stored as zip directory. We can explore other options later if we want.

**Comment by constantinpape** [comment]
It did not get any faster for me, on the contrary seems to take even longer now and I aborted it after some time:
total time: 8:20 min with  compression: 7:02 min

Compared to locally with gzip (only compression): 20 sec

I am on Ubuntu 20 and using ffox 89.0.2 . Note that ffox is not even using much CPU (~40% of one core).

Am I using the right version? This is how it looks during zipping rn:

![Screenshot from 2021-07-14 13-25-41](https://user-images.githubusercontent.com/4263537/125615033-c6286906-c5a1-4b15-bf79-fc93edef6665.png)

**Comment by oeway** [comment]
@constantinpape Sorry, there is [a typo](https://github.com/imjoy-team/bioimage-io-models/commit/b1bb1d4479a53c89c4f80c19d3c526f37523513d#diff-f3583448875890064c55fa919e742e7f53ae5aef92feed2bdad34f569d667a10), so it's not really working.

Please reload the page and try again.

**Comment by oeway** [comment]
Correction: we had compression enabled already. By default, UZIP.js  will do Zlib level=6 compression.

**Comment by constantinpape** [comment]
Ok, it works now, zipping took 55sec for me, so already much better.
Maybe we can decrease the compression level a bit to make it faster; the weights are usually compressed already anyways so higher compression will not bring that much.

**Comment by oeway** [comment]
> Ok, it works now, zipping took 55sec for me, so already much better.
> Maybe we can decrease the compression level a bit to make it faster; the weights are usually compressed already anyways so higher compression will not bring that much.

Did you read the compression time in the console? It said `uzip compression: 30821.0107421875 ms` for me this time (with compression).

Done, now I disabled the compression.

**Comment by constantinpape** [comment]
> Did you read the compression time in the console? It said `uzip compression: 30821.0107421875 ms` for me this time (with compression).

No, I measured with stopwatch app (so there's probably a +- 1 sec error).

**Comment by oeway** [comment]
Oh, by disabling compression, it takes 1.7s to zip it, great progress we are making!

**Comment by constantinpape** [comment]
Yes, now it's super fast, thanks!
Feel free to close the issue.

**Comment by oeway** [comment]
Great, thanks for opening this issue, didn't expect that the jsZip was that slow!

**Comment by constantinpape** [comment]
Awesome!

**Comment by emilmelnikov** [comment]
It would be even better to stream-download the packager output, avoiding large temporary in-memory buffers. [ZIP format](https://en.wikipedia.org/wiki/ZIP_(file_format)#Structure) is definitely amenable to that.

It seems possible to do this in browser via [Streams API](https://github.com/MattiasBuelens/web-streams-polyfill) and Web Workers. There is also https://github.com/jimmywarting/StreamSaver.js, their method is hacky, but works (look at the code).

**Comment by oeway** [comment]
Thought about streaming, but the difficulty is not how to stream saving the zip file,  it is rather about how to do zipping while streaming to the disk. The zipping library needs to support that. JsZip.js does mention that they have streaming support, but they also noted that that means the file headers will stored to the end of the stream, which may make some archiver fail to read the file.

So I assume that might need significant efforts, and we are less likely to have 2~3GB model packages at the moment. 

For long term it would be definitely interesting, e.g. for downloading a dataset. 

Feel free to explore that, I would be really interested in it if you get it to work.
