### ISSUE TITLE
Datasets: best practices and questions

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#147]
I want to add a few datasets to the website to document the training for my models better. However I am currently not quite sure what the best practices for this are. In particular:
- Are there any example rdfs available? I could not find any.
- The "source" button leads to the url of the dataset, and does not show the rdf (as is the case for the model).
   - I think it would be good to have the buttons do the same thing in both cards, so maybe we could change the symbol in the dataset card to something more indicative that this will take you to a new url?
    - I think it would be good to also have a button that displays an rdf in the dataset card.
- What are the requirements for sources? Does it have to be zenodo? I would also like to just link to e.g. https://cremi.org/
- Is it possible to update the dataset rdfs? (I think that would be fairly important)

**Comment by oeway** [comment]
Hi @constantinpape It's good that you started to look into this. We have very loose definition at the moment, here are some examples from zero: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/8ba67e98a894cb271b98fa8da2ec46af46a541fe/manifest.bioimage.io.yaml#L29-L55

The source can be any URI at the moment. So you can basically upload a rdf.yaml file with source=https://cremi.org/... to zenodo. You should be able to do this the same way as you do for models, and you should be able to update it as well (we don't have dedicated UI for dataset though, so you need to edit the yaml file directly).

(also see the dataset RDF discussion [here](https://github.com/bioimage-io/spec-bioimage-io/issues/153))

**Comment by constantinpape** [comment]
Thanks, that's a good starting point! I will see how upload via the website works for this.

**Comment by constantinpape** [comment]
@oeway, I tried uploading a dataset rdf.yaml, but it fails:

https://user-images.githubusercontent.com/4263537/125631379-ee0af536-b137-4c42-910b-432ace72f825.mp4


The console shows the following error:
```
Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    readEndOfCentral chunk-vendors.470b33a2.js:67758
    load chunk-vendors.470b33a2.js:67758
    exports chunk-vendors.470b33a2.js:67758
```

**Comment by oeway** [comment]
Ok, I will fix that!

**Comment by oeway** [comment]
@constantinpape It should been fixed now! Sorry that I forgot to implement the yaml load at all, we treated is as a zip and try to parse with jszip. Please give it a try in the preview (BTW, you can find a bug report button in the netlify preview page located in the lower left corner, if needed you can use that to record screen and fire bug report directly ;).

BTW, I am thinking also to replace the jszip with uzip in the website too.

**Comment by constantinpape** [comment]
@oeway thanks for fixing this, and in theory it works now, but it requires a license in order to upload it.
For datasets that can be a bit difficult, because for many of the datasets I am not actually hosting the data, but just adding a link to the resource so that we can reference it from inside the model-zoo.
For these data-sets I am not sure what license to use...

Edit: I will go with CC-BY-4 for now, but this is something we should discuss.

**Comment by oeway** [comment]
If we just add a link to the RDF, I would actually interpret the license as the license for the RDF file only. The license would apply to the entire dataset if the files are referred in relative path in the same zenodo deposit. 

How about that? We can also add a note for the license definition.

**Comment by constantinpape** [comment]
> If we just add a link to the RDF, I would actually interpret the license as the license for the RDF file only. The license would apply to the entire dataset if the files are referred in relative path in the same zenodo deposit.

Yes, that makes sense but it feels a bit unnecessary to add a license if we just link to some external resource.
But it's not a big deal, we can keep it this way and add some clarification on this.

**Comment by constantinpape** [comment]
@oeway did you see the 2 datasets i uploaded and could you add them to the zenodo community so that they show in the website?

**Comment by oeway** [comment]
@constantinpape I already accepted it a while ago, and I just checked the console log of the website, it doesn't like the cover URL, because we assume the cover image are uploaded to zenodo.

I made it like that because an arbitrary cover image may disappear, or simple because the server doesn't have CORS enabled. 

So it would be better if you can upload include the cover image in the upload, and use a relative file path at least for now. BTW, it seems the image from the URL you provided are rather big, could you provide a smaller file to improve the loading time? e.g. a few hundreds pixels.

Edit: in the future, I can also implement in the upload dialog that we will (try to) pull the external image cover image, resize it and upload to zenodo.

**Comment by constantinpape** [comment]
> So it would be better if you can upload include the cover image in the upload, and use a relative file path at least for now.

Ok, I will fix it.



> BTW, it seems the image from the URL you provided are rather big, could you provide a smaller file to improve the loading time? e.g. a few hundreds pixels.

Ok. Btw, do we suport gifs?

**Comment by constantinpape** [comment]
@oeway I updated the two datasets on zenodo, but still can't see them on the website.

**Comment by oeway** [comment]
> Ok. Btw, do we suport gifs?

Yes, we do


> @oeway I updated the two datasets on zenodo, but still can't see them on the website.

I still see the error from the console from bioimage.io:
```
app.234425ac.js:1 Error: Invalid file identifier: https://grand-challenge-public-prod.s3.amazonaws.com/b/566/banner.x10.jpeg
```

One issue might be that when we update the covers, we somehow miss the metadata on zenodo, these identifiers needed to be updated too:
<img width="485" alt="Screen Shot 2021-07-14 at 10 29 28 PM" src="https://user-images.githubusercontent.com/478667/125688700-1e1a8ae8-5f79-474d-8858-c256040599c5.png">

You updated from the bioimageio upload page, right? I will need to look into it why it doesn't fix the metadata.

**Comment by constantinpape** [comment]
> You updated from the bioimageio upload page, right? I will need to look into it why it doesn't fix the metadata.

No, I updated directly on zenodo. Updating via page was not so easy because it wasn't listed there yet.

**Comment by oeway** [comment]
That's true, ok then you only need to update the URL identifiers manually, you can copy the URL of the cover image from zenodo, then edit and change the identifier URLs for the cover image. 

An example URL for the cover image: https://sandbox.zenodo.org/record/880817/files/input.png 


EDIT: Now you can see the two: https://bioimage.io/#/?type=dataset&id=10.5072%2Fzenodo.881020  so you can also use the edit button to update from bioimage.io.

**Comment by constantinpape** [comment]
Thanks, @oeway. It works now.

**Comment by oeway** [comment]
> Thanks, @oeway. It works now.

Great! BTW, do you see the cover images for this one is broken: https://bioimage.io/#/?type=dataset&id=10.5072%2Fzenodo.881018 Could you try to update it from the upload page?

**Comment by constantinpape** [comment]
> Great! BTW, do you see the cover images for this one is broken: https://bioimage.io/#/?type=dataset&id=10.5072%2Fzenodo.881018

For me it works: 
![Screenshot from 2021-07-15 14-41-46](https://user-images.githubusercontent.com/4263537/125789752-46159346-dc5a-4295-9ace-ae1e7dbd9549.png)

**Comment by oeway** [comment]
@constantinpape I just checked, it only works in firefox, not chrome. Here is the error:

> Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
> https://brainiac2.mit.edu/isbi_challenge/sites/default/files/Challenge-ISBI-2012-sample-image.png

This is another reason for us to upload the coverimage, I think. And I guess you already did, but you just need to update the zenodo meta info, could you click edit button and go through the upload process once more?

**Comment by constantinpape** [comment]
Ok, I will update it later. Unrelated: I pinged you in gitter, could you have a quick look and check why the isbi model is not displayed on the website rn?

**Comment by constantinpape** [comment]
I updated the isbi dataset now and checked that it displays correctly in chrome.
