### ISSUE TITLE
yaml files downloaded with packager are in binary encoding

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#149]
The yaml files are binary encoded after downloading with the packager and extracting via gzip:
```
$ file -i rdf.yaml 
rdf.yaml: application/octet-stream; charset=binary
```

I have checked for this model https://sandbox.zenodo.org/record/880843#.YO85CjqxVH4
and this happens for both the bioimage packager and the ilastik app.

Note that the issue is in the packager, not with the source; the rdf on https://sandbox.zenodo.org/record/880843#.YO85CjqxVH4 is correctly ascii encoded.

This one is urgent! We need it fixed to check the models in ilastik.

**Comment by emilmelnikov** [comment]
I think this is because [`str2ab`](https://github.com/imjoy-team/bioimage-io-models/blob/30671815b8d4cc4b3e0b1b27730a747a0d3ecce1/src/bioimageio-packager.imjoy.html#L233) tries to encode a string as UTF-16?

```
$ hexdump -C rdf.yaml | head -3
00000000  66 00 6f 00 72 00 6d 00  61 00 74 00 5f 00 76 00  |f.o.r.m.a.t._.v.|
00000010  65 00 72 00 73 00 69 00  6f 00 6e 00 3a 00 20 00  |e.r.s.i.o.n.:. .|
00000020  30 00 2e 00 33 00 2e 00  32 00 0a 00 74 00 79 00  |0...3...2...t.y.|
```

Text files should probably be encoded as UTF-8, with

```javascript
files2zip["rdf.yaml"] = new TextEncoder().encode(jsyaml.dump(exportSpec))
```

**Comment by oeway** [comment]
Nice catch @emilmelnikov  ! I will fix that.

**Comment by oeway** [comment]
This is now fixed, thanks you all!
