### ISSUE TITLE
id field in the downloaded model

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#152]
The downloaded model has an `id` field (which contains the id for bioimage.io).
However, this is currently not part of the spec, so the model will fail validation due to that.
There are two ways to fix this:
- Move the `id` field to `config`
- Add `id` as optional field to the spec

@oeway I would prefer the first solution, but if your code hinges on this in many places we can also add it to the spec.

**Comment by constantinpape** [comment]
cc @k-dominik @FynnBe

**Comment by oeway** [comment]
Hi, I think we can go for option 1, but that will require some more time to fix and test as the id is an important key for the website.
I suggest that we fix it from the packager for now.

**Comment by oeway** [comment]
Fixed with https://github.com/imjoy-team/bioimage-io-models/commit/1a71de33101132ff02e5da21cd0613b89bcbf0c5
