### ISSUE TITLE
Hackathons

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#163]
As discussed last Friday https://github.com/bioimage-io/bioimage.io/issues/28#issuecomment-881508842, it would be good to keep the momentum and have one or two hackathon days to make progress towards the functionality we need for the preprint.
As far as I recall, we discussed two options:
- Have an in-person (or hybrid) hackathon in Heidelberg. Would make sense to have 2-3 consecutive days for this.
- Have remote hackathon(s). Could be single day, e.g. starting next Friday.

cc @akreshuk @oeway @esgomezm @FynnBe

**Comment by esgomezm** [comment]
Hi @constantinpape 

I'm available for any remote hackathon. For the in-person one, I'm not sure about the current restrictions in Germany. Very recently it was mandatory to fulfill a 10 days quarantine, at least when traveling from Spain :v: , could you please ask at your institution?

**Comment by constantinpape** [comment]
> Very recently it was mandatory to fulfill a 10 days quarantine, at least when traveling from Spain

The current rules say that entering from a risk area requires a 10 day quarantine, https://www.bmi.bund.de/SharedDocs/faqs/EN/topics/civil-protection/coronavirus/quarantine/do-people-entering-germany-have-to-go-into-quarantine.html, however it is possible to prevent this " by submitting a certificate of recovery, a certificate of vaccination or proof of a negative test result". Also, "If you previously stayed in in a high incidence area, you must wait at least five days before taking a test.". Given that Spain is a "basic risk area" (see https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Transport/Archiv_Risikogebiete/Risikogebiete_aktuell_en.pdf?__blob=publicationFile) this 5day limit should not apply.

> could you please ask at your institution?

It would indeed be best to double check this with EMBL and clarify their current policy for visitors. @akreshuk can you please reach out to HR about this?

**Comment by oeway** [comment]
Hi, I am now quite certain that I won't be able to join the onsite hacakthon, but virtual hackathon would be an option. Next Friday would work for me.

**Comment by constantinpape** [comment]
> Hi, I am now quite certain that I won't be able to join the onsite hacakthon, but virtual hackathon would be an option. Next Friday would work for me.

Ok, then let's plan virtually!
So how about we do it Friday (23rd)? Let's say starting at nine with some discussions? We can also already gather the topics to work on. I will focus on the python library, see https://github.com/bioimage-io/python-bioimage-io/issues/74.

**Comment by oeway** [comment]
Sounds good! Friday 23rd, 9:00 then.

> So how about we do it Friday (23rd)? Let's say starting at nine with some discussions? We can also already gather the topics to work on. I will focus on the python library, see bioimage-io/python-bioimage-io#74.

Please also add it here in the project: https://github.com/orgs/bioimage-io/projects/3 (Esti already added some items there).

**Comment by constantinpape** [comment]
> Please also add it here in the project: https://github.com/orgs/bioimage-io/projects/3 (Esti already added some items there).

It's in there already; I also added a Hackathon column.

Also, now that we do it virtually we can easily accomodate more people, so feel free to tag anyone who might be interested here.

**Comment by FynnBe** [comment]
@tomburke-rse might be interested?

**Comment by tomburke-rse** [comment]
He is, but he is also on vacation ;-) I won't be able to attend. Maybe someone else from the Jug-Group? @fjug

**Comment by esgomezm** [comment]
I tag @ccrtorreg

**Comment by constantinpape** [comment]
We (@FynnBe, @k-dominik, @akreshuk, me) just realized that we have a group meeting at 9.30.
I suggest we still meet at 9 to discuss the plan for the day until 9.30 and then reconvene after our group meeting (~ 10.30); and the ones not part of it can of course continue discussions or start hacking.

also tagging @Steffen-Wolf, who might be interested to join and work on the online mutex watershed app.

**Comment by esgomezm** [comment]
ZeroCostDL4Mic team @Romain-Laine @guijacquemet @paxcalpt

**Comment by constantinpape** [comment]
We had a very successful hackathon today and decided to do the same again next Friday, but start a bit later (9:30). 
We will continue working on the projects started this week and also try to focus a bit more on CI.
Everyone interested is welcome to join.
