### ISSUE TITLE
Can't deposit a new model

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#165]
@oeway I am trying to upload a new deposit, but it fails; see screenshot below.

Here's the link to the model: https://oc.embl.de/index.php/s/nrpq7NDTPmkIOdf

![Screenshot from 2021-07-23 16-57-08](https://user-images.githubusercontent.com/4263537/126802086-8819c1ab-5f84-45a2-9efc-f355b2392a0e.png)

**Comment by oeway** [comment]
Hi, I just tried it and it does happen to me after uploading it for a while. I believe it's coming from the server, in the log it said "The server could not verify that you are authorized..." even though we passed the right token to it.  I logged out and logged in again, the error seems gone now. Do you have multiple account? Could you try to log in and out and give it another try. We might messed up with caching the credential.

**Comment by constantinpape** [comment]
Yes, I logged out and in again, it works now.
(And there's a new model for you to accept ;))
