### ISSUE TITLE
List of models manifest.bioimage.io.json

### ISSUE THREAD

**Issue by dasv74** [bioimage-io/archive.bioimage.io#172]
Previously the list of all models of the zoo was summarized in this json file:
https://raw.githubusercontent.com/bioimage-io/bioimage-io-models/gh-pages/manifest.bioimage.io.json

This list seems not updated with new models, did I miss something?

**Comment by oeway** [comment]
Hi, right, that file is not updated for zenodo models. We are in the
process of making a new repo with a json file generated from zenodo, I wil
let you know when we are done.

**Comment by dasv74** [comment]
OK. "deepImageJ Instal Models" uses this json file. 

If it is a manual operation of copy/paste, I can ask to one of my students to update this list.

**Comment by oeway** [comment]
@dasv74 Yes, in the meantime you can do that too

**Comment by oeway** [comment]
@dasv74 The website is switched its source to : https://github.com/bioimage-io/collection-bioimage-io/blob/gh-pages/rdf.json

You can use the same one or host a copy of it in the deepimagej repo for deepimagej.

**Comment by oeway** [comment]
I will close this for now, feel free to reopen if you have further question.
