### ISSUE TITLE
Partners component is off-center

### ISSUE THREAD

**Issue by junelsolis** [bioimage-io/archive.bioimage.io#177]
The `Community Partners` component is off-center. It appears okay on mobile to medium viewports but bleeds out of the container on larger viewports. The text _Community Partners_ also needs more padding from the previous section. I would like to write a pull request to fix this.
 
![image](https://user-images.githubusercontent.com/11444749/137544686-0363eb57-8f56-4334-9e29-c65fa0c4e83b.png)

**Comment by oeway** [comment]
Hi @junelsolis Thanks for the report, please do!

**Comment by oeway** [comment]
Due to inactivity, we will close this PR for now, please feel free to reopen.
