### ISSUE TITLE
Validation when uploading a model gets stuck

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/archive.bioimage.io#178]
Hi @oeway @FynnBe @constantinpape 

I'm trying to upload a model but the validation seems to get stuck. Here you have the log. Please let me know if you need anythin else:

![Screenshot 2021-10-18 at 13 39 43](https://user-images.githubusercontent.com/43643518/137732320-ace44400-13f3-428e-88ba-73ed9a254f3b.png)

Just note, while the validation does not pass, we cannot upload any new model.

Thank you!

**Comment by constantinpape** [comment]
This looks like something @oeway has to debug.
What browser and version are you using @esgomezm?

**Comment by oeway** [comment]
@esgomezm and @constantinpape Thanks for the report, I managed to reproduce in firefox and have now [fixed it](https://github.com/imjoy-team/imjoy-core-plugins/commit/aac0206d5a39f8af5e82918a15f06ee4ae32057a), please try it again.

Please close the issue if it works for you. @esgomezm 

This happens because we are waiting for the next release of pyodide so we are using the dev branch of the library, but recently they have deprecataed the pyimport function.

**Comment by esgomezm** [comment]
It's still not working:

![Screenshot 2021-10-18 at 19 23 54](https://user-images.githubusercontent.com/43643518/137793498-1e210c31-8447-4f37-ab33-82c4c6e6741c.png)

**Comment by esgomezm** [comment]
Ok, so it works but after passing it, I cannot click on OK

![Screenshot 2021-10-22 at 14 36 04](https://user-images.githubusercontent.com/43643518/138463029-e8de0fd7-d447-4ef8-87eb-5e76a1c28636.png)

**Comment by oeway** [comment]
Hi @esgomezm Could you check if you have other required fields filled correctly?

**Comment by esgomezm** [comment]
All of them were correctly field as far as I saw. No red or warning labels

**Comment by esgomezm** [comment]
I think this one was fixed

**Comment by esgomezm** [comment]
Sorry... it seems it's not solved
![Screenshot 2021-11-11 at 16 49 18](https://user-images.githubusercontent.com/43643518/141336790-6a505ff0-f4ac-449e-81a8-6e1b82b01f92.png)

It gets stucked in the validation

**Comment by constantinpape** [comment]
@oeway could you please double check this?
@esgomezm can you send the model to Wei so he can debug this?

**Comment by oeway** [comment]
Sure, I need the model to test indeed.

**Comment by esgomezm** [comment]
sure!

**Comment by oeway** [comment]
@esgomezm I just tried it, you cannot click ok because the license field is not filled, not the validation.

In your RDF you have license: BSD-2, which is not in the list of [SPDX](https://spdx.org/licenses/), so you need to select for example BSD-2-Clause. Unfortunately, the UI library didn't highlight that part.

But now I am wondering why the validation passes, @FynnBe I thought the validator will complain if the license field is invalid.

cc @constantinpape

**Comment by FynnBe** [comment]
> But now I am wondering why the validation passes, @FynnBe I thought the validator will complain if the license field is invalid.

we warn about it:  `UserWarning: BSD-2 is not a recognized SPDX license identifier. See https://spdx.org/licenses/`
This was due to models being published before we wanted to fix it to SPDX and thus we reserved the enforcing of SPCX licenses for a future version.

**Comment by oeway** [comment]
> > But now I am wondering why the validation passes, @FynnBe I thought the validator will complain if the license field is invalid.
> 
> we warn about it: `UserWarning: BSD-2 is not a recognized SPDX license identifier. See https://spdx.org/licenses/` This was due to models being published before we wanted to fix it to SPDX and thus we reserved the enforcing of SPCX licenses for a future version.

@FynnBe Could you perhaps redirect the warnings to the validator output? Maybe it's a time to enforce the rules?

**Comment by constantinpape** [comment]
> > 
> 
> @FynnBe Could you perhaps redirect the warnings to the validator output?

Yes, I think we should add `warnings` as another field.

> Maybe it's a time to enforce the rules?

I would personally wait with this. It will be difficult enough to get all the deepimagej models to pass the validation as it stands right now...

**Comment by esgomezm** [comment]
> @esgomezm I just tried it, you cannot click ok because the license field is not filled, not the validation.

Sorry for this! I couldn't see the field in red as missing. I'm uploading it. It will take some minutes.

> I would personally wait with this. It will be difficult enough to get all the deepimagej models to pass the validation as it stands right now...

I think you can do it as long as there's a message pointing to this field. Note also that one of the things we will do during the hackathon is migrate absolutely the deepImageJ models, making sure that they pass the specifications. Also to try to get the largest number of models crosscompatible, despite having clean and clear use cases

**Comment by oeway** [comment]
I think this is resolved now, please reopen if needed.
