### ISSUE TITLE
Validation that works locally fails for uploader

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#207]
I have a model for which the validation works locally, but fails in the uploader with
```
Error: {
  "name": "{name: NucleiSegmentationAffinityModel, ...}",
  "source_name": "{name: NucleiSegmentationAffinityModel, ...}",
  "error": {
    "outputs": {
      "0": {
        "data_range": {
          "0": [
            "Field may not be null."
          ],
          "1": [
            "Field may not be null."
          ]
        }
      },
      "_schema": [
        "Could not check for duplicate output tensor names due to another validation error."
      ]
    }
  },
  "warnings": {
    "license": "CC-BY-4.0 (Creative Commons Attribution 4.0 International) is not approved by OSI"
  },
  "nested_errors": {}
}
```
I think I know the issue here: the model has outputs
```
- axes: bcyx
  data_range: [-.inf, .inf]
```
and the `[-.inf, .inf]` is turned into some weird string by the js yaml library that then fails validation.
This model is available here: https://oc.embl.de/index.php/s/m3XgcsCFBZofgmC

@FynnBe @oeway it would be important to fix this to enable smooth uploading.

**Comment by FynnBe** [comment]
this is the classic yaml 1.2 vs yaml 1.1 issue... @oeway please make sure that the uploader uses yaml 1.2

(that's why in python we use ruamel.yaml (suports yaml 1.2) and not pyyaml (only yaml 1.1)
