### ISSUE TITLE
Some issues with upload

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#211]
There are two minor issues with the uploader. I observed this when uploading https://zenodo.org/record/5764893#.Ya-hqbso_JU.

### Maintainers

The `maintainers` field is not auto-populated from the rdf.yaml and the name is marked as mandatory but should be optional (we had a very long discussion about this and should stick with the conclusion of it!), see
![Screenshot from 2021-12-07 18-50-49](https://user-images.githubusercontent.com/4263537/145083309-774ec9fb-a10b-4317-8c31-1e98cabd30dd.png)

### Tags

When importing the `tags` from the rdf.yaml they are marked as `The tags field format is invalid`:
![Screenshot from 2021-12-07 18-51-03](https://user-images.githubusercontent.com/4263537/145083395-9254e220-2429-4c8b-b979-74f9e95dbc14.png)
After some removing and re-adding of the tags it works.

**Comment by oeway** [comment]
Thanks for reporting, it was a fast implementation and the input components are shared with the `authors` field. I will improve it when I get some bandwidth on it.

**Comment by constantinpape** [comment]
@oeway both of these issues still exist and especially the one with the tags is annoying, because it appears although the tags are valid.

**Comment by oeway** [comment]
@constantinpape Could you provide more details on how to reproduce the issue of the tags? I tried to import  the rdf file directly, from zenodo doi, and they seems all work.

**Comment by constantinpape** [comment]
@oeway maybe it only happens when importing from zip?! I can easily reproduce it for new models, e.g.
![tag-issue](https://user-images.githubusercontent.com/4263537/149521660-9cd9b5f5-2b1f-418a-9875-1b6b45d3269d.png)
 when trying to import this model: https://oc.embl.de/index.php/s/KtXrlvh1IjqzX9D

**Comment by constantinpape** [comment]
I am using `Mozilla Firefox 96.0` on Ubuntu 20.04

**Comment by constantinpape** [comment]
@oeway Ok, I realized now that the tag issue is because some of the tags I used were upper case, which is not allowed.

This behaviour is however very very confusing, because the tags listed in https://github.com/bioimage-io/bioimage.io/blob/main/site.config.json#L115-L158 use upper case letters (this is what I used as reference for selecting tags).

I suggest we make this consistent and either make all tags lower case in the site.config.json or allow upper case.

**Comment by oeway** [comment]
@constantinpape Right, the preconfigured tags are not valid, I have fixed them and also added an auto conversion step to make sure the newly loaded tags are in lower case. The loading of maintainers should also work now, I will set the name the same as github_user for now to avoid more work on the author input UI. Will close this for now and feel free to reopen if there is still more issue.

**Comment by constantinpape** [comment]
Thanks! This part of the uploader is working now.
