### ISSUE TITLE
Upload with newest format version fails

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#216]
I tried to upload a new model with format version 0.4.2, but this fails because the website still expects 0.4.0:

The validate button throws the following error:
```
Error: {
  "name": "{name: CovidIFCellSegmentationBoundaryModel, ...}",
  "source_name": "{name: CovidIFCellSegmentationBoundaryModel, ...}",
  "error": {
    "format_version": [
      "Must be one of: 0.4.0."
    ]
  },
  "warnings": {},
  "nested_errors": {}
}
```

I think this could be fixed by just using the latest version of the `bioimageio.spec` for validation.

**Comment by oeway** [comment]
Upgraded to `0.4.2.post1`, thanks for the report.

**Comment by constantinpape** [comment]
Unfortunately this doesn't fix the issue (or to be more precise introduces another issue), now the validation hangs and I get the following error in the console:
```
Error in Plugin BIO-RDF-Validator_sx9le1642099809844: Error: PythonError: Traceback (most recent call last):
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 415, in eval_code
    CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 296, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 4, in <module>
  File "/lib/python3.9/site-packages/bioimageio/spec/__init__.py", line 4, in <module>
    from . import collection, model, rdf, shared
  File "/lib/python3.9/site-packages/bioimageio/spec/model/__init__.py", line 1, in <module>
    from . import v0_3, v0_4
  File "/lib/python3.9/site-packages/bioimageio/spec/model/v0_3/__init__.py", line 1, in <module>
    from . import converters, raw_nodes, schema, utils
  File "/lib/python3.9/site-packages/bioimageio/spec/model/v0_3/converters.py", line 7, in <module>
    from . import raw_nodes, schema
  File "/lib/python3.9/site-packages/bioimageio/spec/model/v0_3/schema.py", line 304, in <module>
    class OutputTensor(_TensorBase):
  File "/lib/python3.9/site-packages/bioimageio/spec/model/v0_3/schema.py", line 323, in OutputTensor
    f"{get_ref_url('function', '_predict_with_tiling_impl', 'https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/prediction.py')}). "
  File "/lib/python3.9/site-packages/bioimageio/spec/shared/utils/_docs.py", line 28, in get_ref_url
    import requests  # not available in pyodide
ModuleNotFoundError: No module named 'requests'
```

**Comment by oeway** [comment]
@constantinpape OK, so this means we need to fix it from the spec repo to conditionally import the requests module.

**Comment by constantinpape** [comment]
Yeah, the problem that the design there is pretty unclean because validation and doc generation are intertwined....
I can hotfix it for now, but for a proper solution @FynnBe will need to take a look.

**Comment by oeway** [comment]
> Yeah, the problem that the design there is pretty unclean because validation and doc generation are intertwined.... I can hotfix it for now, but for a proper solution @FynnBe will need to take a look.

I did a quick look and it seems we are try to be smart in resolving github url by making a http request during runtime. This perhaps also means that that validator cannot run without internet.

@FynnBe Can we remove that but use a static URL, we can say for example the `_predict_with_tiling_impl ` in https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/prediction.py . Less ideal but we won't need to resolve the URL for each run of the validator. Or at least do a try catch.

**Comment by constantinpape** [comment]
I have added a hotfix now @oeway that just returns some string (and throws a warning) if requests is not available (we do the same already if there is not internet connection). Could you please upgrade to 0.4.2post2 so that the uploader works again?

**Comment by constantinpape** [comment]
> @FynnBe Can we remove that but use a static URL, we can say for example the `_predict_with_tiling_impl ` in https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/prediction.py . Less ideal but we won't need to resolve the URL for each run of the validator. Or at least do a try catch.

I think it would be even better to not build the documentation strings when just running validation. There is no good reason for doing this.

**Comment by oeway** [comment]
> I think it would be even better to not build the documentation strings when just running validation. There is no good reason for doing this.

Agreed, that's also what I try to say.

**Comment by oeway** [comment]
@constantinpape Upgraded to 0.4.2.post2
