### ISSUE TITLE
No cards rendered on the website

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#217]
There are currently no cards at all available on bioimage.io (neither models, datasets or applications). Here's what I see when I list all:

![Screenshot from 2022-01-15 00-38-03](https://user-images.githubusercontent.com/4263537/149598615-5955a5bb-f90d-4194-b346-a46e6007808c.png)

Note that we now also have some models that should be displayed, e.g. https://github.com/bioimage-io/collection-bioimage-io/blob/main/collection/10.5281/zenodo.5764892/resource.yaml

**Comment by oeway** [comment]
There was an unmerged PR, now it should have been fixed.
