### ISSUE TITLE
Support structured tags and searching

### ISSUE THREAD

**Issue by oeway** [bioimage-io/archive.bioimage.io#22]
Please comment below for the categories we want to use to structure the tags.
  * Modality (type of microscope)
  * Organism (animal, tissue type etc.)
  * Software (imagej, ilastik, imjoy, ...)
  * Model Architecture (UNet, ResNet, ...)
  * Task (Segmentation, Classification, Denoising, ...)

**Comment by FynnBe** [comment]
If we have filters as well these might be better suited as filters:
- Trainable?
- Date? (year?)
