### ISSUE TITLE
Clicking "click here to see the full documentation" does nothing

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#222]
see 
https://user-images.githubusercontent.com/4263537/149632360-1f58ab29-7aa8-4e1d-873c-4e516803f750.mp4

Note that this model has a fairly long doc: https://zenodo.org/record/5847356#.YeMKB_so8UE

**Comment by oeway** [comment]
This should also been fixed now, it's all because the upgrade of the marked library which cause all the markdown related stuff break.
