### ISSUE TITLE
Clicking "Source" in the model card goes to wrong link

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#223]
see
https://user-images.githubusercontent.com/4263537/149632444-a9ef8d98-53f2-4c88-9aad-65b3b98afa9e.mp4

**Comment by oeway** [comment]
This should work again, I think it's the same issue comes from the unexpected dependabot update of `marked` which we used for rendering markdown content
![j1tRGJz40P](https://user-images.githubusercontent.com/478667/149908997-bd79a299-2e35-4213-9ab2-bfdac5ddaa46.gif)
.
