### ISSUE TITLE
Regular model zoo call

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#24]
The idea of having a model zoo call every other week came up.
I think this should be open for everyone interested, but we should coordinate with everyone in the
"core" group. 
Just tagging everyone for whom this is relevant; feel free to tag others for whom this is relevant.
@fjug @akreshuk @oeway @m-novikov @FynnBe @esgomezm @MartinHjelmare @tibuch

**Comment by akreshuk** [comment]
I can suggest some times that don't overlap with any regular meetings for me, and we take it from there. I assume we only have to support the European time zone for now. 

/polls "Monday 2pm" "Monday 3pm" "Wednesday 3pm" "Thursday 3pm" "Friday 1pm" "Friday 2pm" "Friday 3pm"

Hmm, polls option didn't work. But well, you see the times. have your say.

**Comment by esgomezm** [comment]
Super! Any of those times are ok for us @arrmunoz, @dasv74 @carlosuc3m.

**Comment by oeway** [comment]
Great, thanks, any slot listed should work for me.

CC: @haoxusci @cwinsnes @trangle1302 @emmalundberg

**Comment by dasv74** [comment]
I don't understand these series of emails. What shall I do?

Thanks

Best,

Daniel

On 12 Jun 2020, at 17:09, esgomezm <notifications@github.com<mailto:notifications@github.com>> wrote:



Super! Any of those times are ok for us @arrmunoz<https://github.com/arrmunoz>, @dasv74<https://github.com/dasv74> @carlosuc3m<https://github.com/carlosuc3m>.

**Comment by constantinpape** [comment]
@dasv74 we want to set up a regular call (every other week) for the model zoo and wanted to check what times would be good for the initial groups involved in this project.

Ideally we would find a time that does not overlap with any other regular calls, so that at least one member of each group could join regularly.
@akreshuk proposed the following times, which so far seem to be ok with everyone that answered. 

>  "Monday 2pm" "Monday 3pm" "Wednesday 3pm" "Thursday 3pm" "Friday 1pm" "Friday 2pm" "Friday 3pm"

**Comment by emmalundberg** [comment]
All 3pm times are good for me.

**Comment by akreshuk** [comment]
I hope everyone who felt like responding had the time to respond, so let's fix it at Friday 3pm then. As we just had a meeting with @oeway last Friday, I propose to have the next one next Friday, June 26th. The aim of the meeting is to keep the momentum and have everyone on the same page, so fully voluntary, no stress, no obligations. I'll send a zoom invite.

**Comment by oeway** [comment]
Hi all, I created https://github.com/bioimage-io/bioimage.io/issues/28 with a zoom link, a meeting agenda note where every one can add their topic, will also use the same issue to post the meeting notes. This is how Jupyter community do their open meetings, let's see how it works for us @akreshuk

**Comment by esgomezm** [comment]
I add @fjug, @frauzufall and @tibuch to follow the meetings. Previous meeting minutes and Zoom link can be found at bioimage-io/bioimage.io#3
