### ISSUE TITLE
Use "training_data" field to auto generate doc

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#250]
We have a model with the `training_data` field on the website now: https://bioimage.io/#/?id=10.5281%2Fzenodo.5847355
And should use this field to autogenerate a training data section in the model card and also ensure that the id is in the links so that the dataset icon is displayed in the model card.
(This is not super high priority, but I wanted to make sure we don't loose track of this.)

**Comment by constantinpape** [comment]
We have several more models with training_data field now, for example: https://github.com/bioimage-io/collection-bioimage-io/blob/main/collection/10.5281/zenodo.6348084/resource.yaml#L12-L13.
It is still not used to add a link to the model though, see 
![image](https://user-images.githubusercontent.com/4263537/167705179-19f3d7e0-d03f-42e9-95a0-0fe4e013c625.png)

@oeway I think this feature would be important to add now, since we use it pretty centrally in the paper.

**Comment by oeway** [comment]
hey, I think this is important but  the best way to implement this is to resolve it from the collection repo so we can properly validate the dataset field.

I suggest the following: 1) resolve the dataset  validate it and add it as a new resource item 2) replace the training data field with the dataset id if it's not an id already 3) add the dataset link to the model

Cc @FynnBe

**Comment by FynnBe** [comment]
sounds good. However, for now displaying `training_data` like a link should be all we need somewhat urgently. @constantinpape example model already has an id set in `training_data`. 

> 3) add the dataset link to the model

If I understand you correctly you want to append the dataset id to the `links` field. I would suggest that we do that on-the-fly on the website only to display the `training_data` as a link for now. we could change it at some time and show it differently. duplicating the link in `links` and `training_data` in the RDF itself does not make a lot of sense to me. Treating the `training_data` id as a link on the website (for now) does.

To create a dataset RDF "on-the-fly" can be implemented, I'll create an issue to discuss details about this there. I don't think this is urgent.

**Comment by constantinpape** [comment]
Indeed, for now we only have models where we use `training_data: id`. So the rather urgent thing is to append the training data id to the links. @oeway: do you agree that this can/should be done on-the-fly by the website? If yes, can you please implement it?

For the generation of ids from the training data field: indeed it sounds like this should be done by the collection repo, but currently we don't have a model yet that uses this (at least not that I know of), so this is not so urgent.

**Comment by oeway** [comment]
Hey, I think we need to add the links from the collection, not here on-the-fly, keep in mind that the summary file does not contain the `training_data` field, so it's not possible for the website to generate those links when we render the website for the first time. To keep the summary field slim, we don't want to add many fields to it either, so what I suggest is to generate the dataset item then add the id to the `links` of the model.

**Comment by FynnBe** [comment]
I think it is much cleaner to add `training_data` or `training_data_ids` to the collection summary that only has a list of ids (in-place dataset definitions are ignored for now and later made into their own dataset RDFs on-the-fly). Then we don't mingle with the updated RDFs, which are also read through the library. We decided to give `training_data` its own field, now we should follow through with it and don't just merge it back to `links`.  

This will also allow us to make cool things like a joint icon for all training_data that expands to the list of training datasets instead of having 10 training data icons linked that are making it hard to see the more important app icons, etc... Not proposing to implement any of this now, but if we keep our data model clean this kind of follow up development will be easier.

**Comment by oeway** [comment]
> I think it is much cleaner to add `training_data` or `training_data_ids` to the collection summary that only has a list of ids (in-place dataset definitions are ignored for now and later made into their own dataset RDFs on-the-fly). Then we don't mingle with the updated RDFs, which are also read through the library. We decided to give `training_data` its own field, now we should follow through with it and don't just merge it back to `links`.
> 
> This will also allow us to make cool things like a joint icon for all training_data that expands to the list of training datasets instead of having 10 training data icons linked that are making it hard to see the more important app icons, etc... Not proposing to implement any of this now, but if we keep our data model clean this kind of follow up development will be easier.

Well, it doesn't make much difference, there must be some place where we merge the training data to links, either in the collection repo or the website. In other words, we can make the python code cleaner, but by making the javascript code less clean.

The summary file suppose to stay slim since that will affect the user experience, every field we add will have an effect on the file size. That's why I propose to do it in the collection repo.

**Comment by constantinpape** [comment]
I discussed this with @FynnBe earlier, and the main reason for not updating it in the `rdf.yaml` in collections would be that we are downloading this file in the python libraries when a user specifies a model id. So adding the link there is somewhat unclean, because it would add a link that wasn't put there by the user or any subsequent explicit changes in the collection repo.
(For links this will not probably not be too bad of an issue, so we could do it, but there might eventually be other cases where this may cause real issues.)

**Comment by FynnBe** [comment]
maybe to reconcile our goals here we could add the `training_data` id to links only in the collection summary for the preview and keep it separately in the actual rdf? In the preview we treat it as any other link (for now), while the detailed model card "knows" the difference and the actual RDF stays clean.

**Comment by FynnBe** [comment]
> maybe to reconcile our goals here we could add the `training_data` id to links only in the collection summary for the preview...

if we want to change this in the future the change affect only the collection.json summary, not all individual updated RDFs...

**Comment by constantinpape** [comment]
> maybe to reconcile our goals here we could add the `training_data` id to links only in the collection summary for the preview and keep it separately in the actual rdf? In the preview we treat it as any other link (for now), while the detailed model card "knows" the difference and the actual RDF stays clean.

That sounds good.

**Comment by oeway** [comment]
> maybe to reconcile our goals here we could add the training_data id to links only in the collection summary for the preview and keep it separately in the actual rdf? In the preview we treat it as any other link (for now), while the detailed model card "knows" the difference and the actual RDF stays clean.

This works, but I will need to some more fix in the website to make it work. Currently, the standalone rdf file has higher priority and it will overwrite the information we get from the summary file. And not sure if this is a clean solution either.

From what I can see now, there is no real difference between all the discussed solution, there is always tradeoffs. But just to make things move forward without wasting too much time on discussion these tiny details.  I think we can add `training_data` as as summary field for now, and I will fix it from the website.
