### ISSUE TITLE
improvement/nice-to-have: Progress bar / human readable download/packaging progress

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#267]
I'm using the website now quite regularly to download models. What always bothers me a bit is that I can not really interpret the progress of the packager very well.

<img width="514" alt="Screenshot 2022-04-26 at 08 54 34" src="https://user-images.githubusercontent.com/24434157/165240775-d516b851-4d14-4d32-a851-e134360bc1b9.png">

comparing 8, 9, 10 digit numbers is hard for humans. It would be cool to have something maybe in percent, or in a different unit, like MB? Also a global progress would be cool to have (i can see that it might be hard to do this properly, but already in number of files downloaded/files to download would be nice).

Cheers :)

Edit: okay, for some reason I've noticed the progress bar on the bottom of the dialog now for the first time. Maybe it's too subtle.

**Comment by oeway** [comment]
@k-dominik Thanks for the suggestion, I agree!

This should do it: https://github.com/ilastik/bioimage-io-resources/pull/53/files

Would you merge and test it?

**Comment by k-dominik** [comment]
Hey @oeway,

thank you very much for fixing it so quickly. I merged and tested it. Really  on the verge of nitpicking: I don't think we need so many decimal places there...
<img width="398" alt="Screenshot 2022-04-26 at 09 31 39" src="https://user-images.githubusercontent.com/24434157/165246211-4605c682-bf0e-44c3-b398-9a119b7e7005.png">

**Comment by oeway** [comment]
> Hey @oeway,
> 
> thank you very much for fixing it so quickly. I merged and tested it. Really on the verge of nitpicking: I don't think we need so many decimal places there... <img alt="Screenshot 2022-04-26 at 09 31 39" width="398" src="https://user-images.githubusercontent.com/24434157/165246211-4605c682-bf0e-44c3-b398-9a119b7e7005.png">

Hey, oops, I didn't test. Could you apply a `Math.round()` to the size?

**Comment by k-dominik** [comment]
> Hey, oops, I didn't test. Could you apply a `Math.round()` to the size?

okay I went for `.Fixed(2)` just to have something there for smaller files, too (like samples, which could be small, but not super-small)

**Comment by k-dominik** [comment]
with that fixed, I still noticed, that, when going the generic packager route, it will still have the same big numbers as before. But that one doesn't seem to reside in `bioimage-io-resources`? Could you maybe point me to the packager, then I can add the same changes there.

**Comment by oeway** [comment]
It's here: https://github.com/imjoy-team/bioimage-io-models/blob/master/src/bioimageio-packager.imjoy.html

There is another one for deepimagej too: https://github.com/deepimagej/models/blob/master/src/deepimagej-app.imjoy.html

We may need to aggregate all these later.

**Comment by k-dominik** [comment]
> We may need to aggregate all these later.

I agree this is due a refactor with common functionality extracted.

**Comment by oeway** [comment]
@k-dominik Thank you, closing this now!
