### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocks cover image

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#268]
when opening
https://bioimage.io/#/?type=all&tags=ilastik%2Ftorch-em-3d-unet-notebook&id=ilastik%2Ftorch-em-3d-unet-notebook

the cover image is missing
![image](https://user-images.githubusercontent.com/15139589/165710960-a2068259-5c4d-43e6-8d6c-0ad75ef31afb.png)

the browser logs:
```
2 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/constantinpape/torch-em/blob/main/experiments/misc/targets.png with MIME type text/html. 
See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

the cover image url (https://github.com/constantinpape/torch-em/blob/main/experiments/misc/targets.png) looks correct:
https://github.com/bioimage-io/collection-bioimage-io/blob/fa79bf94883d509abce48ed9ec1ce8d462a05af6/rdf.yaml#L1127-L1130

**Comment by oeway** [comment]
Hey, the link for the images should be a "raw" link, while the one you are provided is the link to a webpage.

The raw link should be: https://raw.githubusercontent.com/constantinpape/torch-em/main/experiments/misc/targets.png

**Comment by FynnBe** [comment]
thanks @oeway! good catch.
@constantinpape  I fixed it here: https://github.com/ilastik/bioimage-io-resources/commit/10099650d550e5ef5fa0fb82594ee2363f7edfe1
