### ISSUE TITLE
Generic BioEngine: prediction not working

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#280]
Great to see the GenericBioEngine on the modelzoo website @oeway!
However, it looks like the prediction is not working correctly; see this video for running it for the LiveCell Model:

https://user-images.githubusercontent.com/4263537/168419018-cfb0e4e0-ffd9-4c31-b5a3-52acba9b17d0.mp4

Note that this produces the correct result when doing this in the notebook, so this is most likely due to some issue with running the triton prediction via the website.

**Comment by oeway** [comment]
Hi @constantinpape Thanks for the detailed report, I am looking into it now!

**Comment by oeway** [comment]
This should have been fixed by https://github.com/imjoy-team/imjoy-core-plugins/commit/b01c9b07a1992c7e4958f2b2d149c535ab55131e

You need need to reload a few times to get rid of the browser cached version.

**Comment by oeway** [comment]
I reloaded the site once and be able to get the correct output:
![Screenshot 2022-05-16 at 16 16 45](https://user-images.githubusercontent.com/478667/168613556-12d3cf64-2816-4974-b894-a9e851817829.png)

**Comment by constantinpape** [comment]
Yes, it also works for me now!
