### ISSUE TITLE
Generic BioEngine: change name

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#281]
I think we should eventually change the name to something that makes more sense for users. Some suggestions:
- `RunModelTest`
- `ModelTest`
- `RunDefaultModelTest`
- `DefaultModelTest`
- `RunModelPreview`
- `ModelPreview`
- `RunDefaultModelPreview`
- `DefaultModelPreview`

(But I think it's not high priority, let's fix #280 first)

**Comment by akreshuk** [comment]
In the paper, we call it "Test Run", we can also use it here.
Also, I would change the icon back to the play button, I think it's more intuitive than the giraffe.
