### ISSUE TITLE
GenericBioEngine: Support spec 0.4.6

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#282]
The GenericBioEngine App currently does not work for models with the most recent format version (0.4.6). This should be easy to fix by updating `bioimageio.spec` in the docker container that is running the inference. A model to test this: https://bioimage.io/#/?id=10.5281%2Fzenodo.5749843

**Comment by oeway** [comment]
This is fixed now, I upgraded the bioengine runtime environment to support 0.4.6.
