### ISSUE TITLE
BioImageIOPackager only downloads partial models

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#284]
For example, for this model: https://bioimage.io/#/?id=10.5281%2Fzenodo.6334777 I get only a partial and invalid download, see screenshot:
![download_error](https://user-images.githubusercontent.com/4263537/168621496-40e4e810-e40e-4841-83e9-eb658fb6b60c.png)
Downloading this model with the python library works fine:
```python
bioimageio.core.export_resource_package("10.5281/zenodo.6334777")
```
downloads the full model pacakge.

**Comment by constantinpape** [comment]
Just fyi, this error happens in Firefox, and also Safari (reported by @fjug). Chrome seems to work.

**Comment by oeway** [comment]
@constantinpape I did some update to the packager:

 * https://github.com/imjoy-team/bioimage-io-resources/commit/359b3b643b0b2f278828189e9f3451d31fc24acf
This is to update the axios library which used for downloading, the default timeout is 0 which means no time out, so I am not sure whether the issue can be fixed. I tested in both Safari and FireFox and they works all fine.


 * https://github.com/imjoy-team/bioimage-io-resources/commit/363c0ae07bc76d3464b713bc0f25f1a8da3acbb9
This is a fix for addressing the `failed to download https` issue.

In any case, please test and see if the issue still exists.

**Comment by constantinpape** [comment]
Yes, works much better now, thanks @oeway.
