### ISSUE TITLE
GenereicBioEngine: Link to numpy data if sample data is not available

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#285]
Not all models have sample data, in that case we should link to the numpy test input data, which is always there.
Example model: https://bioimage.io/#/?id=10.5281%2Fzenodo.6334777

**Comment by oeway** [comment]
This is fixed via https://github.com/imjoy-team/bioimage-io-resources/commit/f87e91d30f77d320ce7eda3b52d396d1576dd12c
