### ISSUE TITLE
GenericBioEngineApp: timeouts

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#288]
I tried to test the bio engine app for a few times and it worked twice, but now it does not start for me any more (just circles and then goes back to the website without any message), and I see the following errors in the Console:
```
Error: Error: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.10/site-packages/imjoy_rpc/rpc.py", line 404, in _wait
    result = await result
  File "<exec>", line 114, in setup
  File "/lib/python3.10/site-packages/imjoy_rpc/hypha/websocket_client.py", line 149, in connect_to_server
    await connection.open()
  File "/lib/python3.10/site-packages/imjoy_rpc/hypha/pyodide_websocket.py", line 59, in open
    return await asyncio.wait_for(fut, timeout=self._timeout)
  File "/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

This may be something transient, but can we be more robust against it / at least display a message when this happens?

**Comment by constantinpape** [comment]
Now I get the following error for any model I try:
```
Failed to find model (10.5281/zenodo.5869899) in the BioEngine, error: Method call time out: public/workspace-manager:services.triton-client.execute
```
(both on firefox and chrome)

**Comment by oeway** [comment]
I think this is because the models  you are testing are not cached on the server, so it's currently downloading the files and can take quite some time. We need a way to cache new models actively.

For now the server should come back once they are done. I have a working PR to allow downloading in the background and return immediately if not available. Will need some time to deploy to denbi cloud.

**Comment by constantinpape** [comment]
Fixed now
