### ISSUE TITLE
Can we create a wiki in this repo?

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/archive.bioimage.io#310]
Hey there,

It's becoming a bit complex to keep track of how the BioImage Model Zoo works for us (testing and curating new contributions etc.) + there will be/are newcomers. Maybe we could have very simple indications about how we (as maintainers) usually proceed. Anna was suggesting a wiki in this repo, but I don't see a way to create it. We can also have it in a different repo.

How does it sound? @oeway can you create a wiki in this repo and I will write some things?

@FynnBe @constantinpape @lmoyasans

**Comment by constantinpape** [comment]
I enabled the wiki @esgomezm: https://github.com/bioimage-io/bioimage.io/wiki
