### ISSUE TITLE
Icy would like to join as a partner.

### ISSUE THREAD

**Issue by tinevez** [bioimage-io/archive.bioimage.io#328]
Hi all,

Following the impressive work by @carlosuc3m Icy is ready to consume models from the zoo, with a dedicated end-user Icy plugin that will be released soonish (2-3 weeks).

To this regards, Icy would like to join as a partner on the website. I prepared a skeleton file as recommended by @oeway 

https://gitlab.pasteur.fr/bia/icy-bioimage-io-resources/-/blob/main/collection.yaml

Can you tell me what are the next steps?

**Comment by carlosuc3m** [comment]
I moved the issue to the collections repository https://github.com/bioimage-io/collection-bioimage-io/issues/542
