### ISSUE TITLE
cannot update models any more

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/archive.bioimage.io#342]
Hi hi!
I'm trying to correct the model https://bioimage.io/#/?tags=bacillus-subtilis&id=10.5281%2Fzenodo.7261974 but it does not allow me to upload a new version: 

<img width="1203" alt="Screenshot 2023-03-27 at 18 49 49" src="https://user-images.githubusercontent.com/43643518/228024891-47dbc055-b95e-43a4-a5bc-3c5a5aa5a469.png">
<img width="1074" alt="Screenshot 2023-03-27 at 18 49 36" src="https://user-images.githubusercontent.com/43643518/228024902-66893c14-15e5-4ffb-9244-5bc98eb29223.png">

**Comment by FynnBe** [comment]
> seems to be working now

https://github.com/bioimage-io/collection-bioimage-io/issues/571#issuecomment-1486910574
