### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jkh1** [bioimage-io/archive.bioimage.io#387]
The link to the Resource Description File Specifications for the [supported formats](https://bioimage.io/docs/#/bioimageio_preprocessing_spec) on the [contribute models page](https://bioimage.io/docs/#/contribute_models/README) is broken (returns 404).
EDIT: This link is also broken: The model is expected to be cross-compatible among the [consumer software](https://github.com/bioimage-io/spec-bioimage-io/blob/master/supported_formats_and_operations.md#consumers),

**Comment by cfusterbarcelo** [comment]
Hi @jkh1,

The supported formats are now clearly specified in [the documentation for the specifications](https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/user_docs/model_descr_latest.md). This update is also reflected in the model section of the documentation, which you can find [here](https://bioimage.io/docs/#/guides/developers-guide?id=models-in-the-bioimage-model-zoo).

Regarding cross-compatibility with consumer software, the specific link that addressed this has been removed. Consumer software refers to the tools or Community Partners that are capable of utilizing the models available in the BioImage Model Zoo. More information about this can be found [here](https://bioimage.io/docs/#/guides/user-guide?id=using-bioimage-model-zoo-models-in-different-software).

Let me know if you need further clarification!
