### ISSUE TITLE
resolve urls to file names in RDFs

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#388]
actually before due to files hosted on zenodo (and not on gh-apges of the old collection repo where we hosted the updated RDFs) we did not have relative paths in the RDFs, so there was a change.

The website needs to resolve relative paths (file names as we don't support folders, aka anything website relevant that does not start with 'http') with the 'parent url' of the rdf url the website is showing content for.

_Originally posted by @FynnBe in https://github.com/bioimage-io/collection/issues/49#issuecomment-2082550035_

**Comment by esgomezm** [comment]
Related, there are broken links to url for the weights here  https://bioimage.io/docs/#/guides/developers-guide?id=model-documentation
![Screenshot 2024-06-04 at 15 02 10](https://github.com/bioimage-io/bioimage.io/assets/43643518/cebcefe2-e723-4dbb-a09b-38a4bf0f30c2)

**Comment by FynnBe** [comment]
> Related, there are broken links to url for the weights 

@esgomezm this is a separate issue...

**Comment by FynnBe** [comment]
I checked a resource with a relative path and it is not working yet:
```
TypeError: e.id.toLowerCase is not a function
    at app.b512ec0e.js:1:1
    at Array.filter (<anonymous>)
    at c (app.b512ec0e.js:1:1)
    at st (app.b512ec0e.js:1:1)
    at app.b512ec0e.js:1:1
    at l (chunk-vendors.e93c4e7e.js:51127:1)
    at Generator._invoke (chunk-vendors.e93c4e7e.js:51127:1)
    at forEach.e.<computed> [as next] (chunk-vendors.e93c4e7e.js:51127:1)
    at n (chunk-vendors.e93c4e7e.js:1:1)
    at s (chunk-vendors.e93c4e7e.js:1:1)

```
using https://bioimage.io/#/?repo=https%3A%2F%2Fuk1s3.embassy.ebi.ac.uk%2Fpublic-datasets%2Fbioimage.io%2Fcollection.json&type=dataset&id=zero%2Fdataset_stardist_brightfield_zerocostdl4mic

preview works: 
![image](https://github.com/bioimage-io/bioimage.io/assets/15139589/43a26878-211d-4110-a839-a3f20a003274)

but the card does not expand and the image disappears after attempting to open the card.
![image](https://github.com/bioimage-io/bioimage.io/assets/15139589/5b05a092-eb05-42fe-922b-f3c1d270479b)

The issue is that the relative path is either not resolved at all or resolved using the `id` field, but as the `id` might be a legacy id, relative file paths should be resolved using the `nickname` field instead.
Of course it is possible to move all files around and save them under legacy paths, but as we are slowly moving to our new ids and this is a very small change to the website I'd much prefer the website to be updated in this manner (resolving relative pahts with the `nickname`, not the `id` field).

**Comment by cfusterbarcelo** [comment]
Hi @FynnBe ,
I've seen that [this issue](https://github.com/bioimage-io/collection/issues/49) has been solved. Is this one solved too?

**Comment by FynnBe** [comment]
yes
