### ISSUE TITLE
Dead links on Zenodo

### ISSUE THREAD

**Issue by haesleinhuepf** [bioimage-io/archive.bioimage.io#395]
Hi all,

I just noticed that links to RDF packages pointing from zenodo don't work. Example:

https://zenodo.org/records/6817639

If you click on the RDF link on that page you get an error message from bioimage.io:

![image](https://github.com/bioimage-io/bioimage.io/assets/12660498/a109a8f5-bfa1-4b83-b7f4-e22209486162)

Also, beginner might not know what RDF packages are. People stumbling over the models on Zenodo might not have any idea what to do with them. If the zenodo description is auto-generated, consider adding an explanatory sentence there.

CC @constantinpape

**Comment by esgomezm** [comment]
Hi @haesleinhuepf 

Thanks for highlighting this one! We are moving away from Zenodo and close to releasing a new model contribution system. Hopefully with that, this issue will be fixed!

**Comment by haesleinhuepf** [comment]
Hi @esgomezm ,

thanks for the feedback! Just out of curiosity: Will the links on zenodo stay dead links then? May there be any chance to make them point to a place where users see how to download a given model with the new infrastructure?

Thanks!

Best,
Robert

**Comment by esgomezm** [comment]
Hi @haesleinhuepf 

The links are not dead, as the files remain in zenodo repositories. Yet another thing is whether a zenodo repository was at any time, a valid model in the zoo and therefore, a model from the BioImage Model Zoo. This content should always be searched and accessed from the BioImage Model Zoo, to avoid any confusion. We encourage anyone to use our site to search for bioimage model zoo models rather than Zenodo or any other storage platform we cannot always maintain or control.

**Comment by haesleinhuepf** [comment]
> The links are not dead, as the files remain in zenodo repositories.

The zenodo repositories come with a link in the description (see screenshot above). This link leads to an error message. There is nothing else in the description. Hence, if people search on zenodo for models and find your model, they have no chance to know what to do with it. Consider updating the error message to be more helpful 😉

**Comment by esgomezm** [comment]
Yes, accepted models have all the links correctly. What I'm trying to explain is that this is not a model from the BioImage Model Zoo, and in reality, it is not even a model. It is not validated or correct, and people should not search for BioImage Model Zoo models in Zenodo but in the BioImage Model Zoo. The main issue here is that as far as we know, Zenodo repositories cannot be removed so this record (or any incorrect one) will remain there. Do you know how to do so by any chance? Thanks

**Comment by haesleinhuepf** [comment]
Well the idea of a long-term archive such as zenodo is that things published there cannot be deleted. Data authors could modify the description with the broken link by releasing a new version of the data though 

Do you think it would be possible to modify the error message in the model zoo with the information you just provided? I think it would be helpful for users and also could encourage users to search in the bioimage website instead if zenodo. 😉

**Comment by constantinpape** [comment]
@haesleinhuepf can you maybe explain how you happened to find this model? Because this looks like a failed upload, which should not be listed in the modelzoo at all. (Neither in the old system where models where stored directly on zenodo, nor in the new system where models are hosted on EBI S3 instead.)

**Comment by haesleinhuepf** [comment]
I went through the Bioimage-io community resources:

 https://zenodo.org/communities/bioimage-io/records?q=&l=list&p=1&s=10&sort=newest

There are plenty of such records with broken links

**Comment by constantinpape** [comment]
> There are plenty of such records with broken links

Yes, these are models where the upload process went wrong. As @esgomezm mentioned these are not models that are not actually available on the zoo. I don't think we can / should do much about this.

We should probably mark the `bioimage-io` zenodo community as deprecated in our docs.
