### ISSUE TITLE
EBI S3 down?

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#396]
It appears that the models on EBI S3 can currently not be downloaded. See https://github.com/computational-cell-analytics/micro-sam/issues/618.

Are we aware of this already? Any ideas why?
cc @oeway

**Comment by oeway** [comment]
Hi I see, the model is already published, so you can access it via https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/idealistic-rat/1/files/vit_l_decoder.pt instead. Note that the previous link contains `staged` which means it's not a published model, so the URL is not guaranteed to be available.

**Comment by constantinpape** [comment]
Ok, thanks!
