### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#400]
Related, there are broken links to url for the weights here  https://bioimage.io/docs/#/guides/developers-guide?id=model-documentation
![Screenshot 2024-06-04 at 15 02 10](https://github.com/bioimage-io/bioimage.io/assets/43643518/cebcefe2-e723-4dbb-a09b-38a4bf0f30c2)

_Originally posted by @esgomezm in https://github.com/bioimage-io/bioimage.io/issues/388#issuecomment-2147621959_

**Comment by cfusterbarcelo** [comment]
This was solved some time ago. Thanks for pointing it out!
