### ISSUE TITLE
Support for various cover image suffixes

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#412]
The cover images for [stupdendous-sheep])https://bioimage.io/#/?type=model&tags=empanada&id=stupendous-sheep)
are not displayed (.tif cover images).
The preview using the thumbnails work. The thumbnails are saved as .png images).

Which of these file formats does the website support?
(Here is a list of the allowed cover image suffixes according to the current spec)
 - .gif
 - .jpeg
 - .jpg
 - .png
 - .svg
 - .tif
 - .tiff

**Comment by FynnBe** [comment]
offline @oeway stated that the website currently cannot handle .tiff-files

**Comment by FynnBe** [comment]
.tiff files are actually not allowed in the latest spec versions anymore...

**Comment by FynnBe** [comment]
we need to manually update older RDFs using tif cover images though...

**Comment by oeway** [comment]
> we need to manually update older RDFs using tif cover images though...

Previously we have a conversion when generating the cover, so maybe we can just run that for all the older RDFs?

**Comment by FynnBe** [comment]
yes, but that thumbnail is also downscaled a bit.
I fixed it manually for the one model that made me discover this issue and it might have been the only one. I couldn't find another, but haven't searched through them all. 
 I think we can close this issue though and if we encounter another case just fix it manually.
