### ISSUE TITLE
Help uploading model

### ISSUE THREAD

**Issue by danifranco** [bioimage-io/archive.bioimage.io#416]
Hi,

I'm trying to upload a model but I'm having a few issues that are a bit cryptic for me:

![image](https://github.com/user-attachments/assets/1afa3525-552b-448d-aac3-767013de94a9)

Is there any doc I can check to understand a bit better the errors? For example, the table suggests that `format_version` field was not provided but it is inside the .yaml file already (`format_version: 0.5.3`).

I uploaded model's zip to Drive in case you want to quickly check it: https://drive.google.com/file/d/155HC7C6oF4o67r_4aE401cUn_Ggaqn_8/view?usp=sharing

Apart from that, I see that model name, description, authors and maintainers are a must in the form. I've already written that info in the .yaml file so maybe they should be filled automatically? If I need to set them again which values are going to be preserved? the ones provided in the yaml or in the web form? 

Thank you so much!

@oeway @FynnBe @cfusterbarcelo

**Comment by FynnBe** [comment]
Seems like there is an issue in the front end causing the `format_version` field to be missing when running the validation!?

**Comment by danifranco** [comment]
Now seems that there is a problem in the page and the validation can not be done:
![image](https://github.com/user-attachments/assets/d5a8320a-2264-40aa-999c-d43161bbe862)

Can anyone check this please? 

Btw, I just saw that BiaPy icon is not present in the model cards (seems that a rollback has been done?)

Putting @esgomezm in the loop!

**Comment by oeway** [comment]
Hi @danifranco thanks for the report, there seems to be a network interruption on the server side, I just manually restarted the service and it should work now , please check.

**Comment by FynnBe** [comment]
now I just got the error again:
![image](https://github.com/user-attachments/assets/0e7f52e9-5d2b-4489-85f5-f7e79154b7a0)

(for https://bioimageio-uploader.netlify.app/#/status)

**Comment by danifranco** [comment]
Yeah, still not working...

**Comment by oeway** [comment]
> Yeah, still not working...

Sorry, there seems to be some service instability, coming from the fact that the previous implementation mixing asynchronous code with synchronous in Python.

I have upgraded to a newer version of the hypha server and it suppose be more stable now, please let me know if it works now.

**Comment by danifranco** [comment]
Now I can validate the model correctly but still some issues during upload:

```
Oops! Something went wrong 😟

Please review the error, and try again. If the issue persists, please contact support

😬 Error calling bioimageio-bot, please report the issue to the admin team of bioimage.io: Error: 😬 Failed to reach to the bioimageio-bot, please report the issue to the admin team of bioimage.io: Message: Traceback (most recent call last): , File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 110, in wrapper data = await handler(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 258, in stage return await notify_ci(CI_STAGE_URL, inputs, context=context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 191, in notify_ci resp = requests.post(url, data=json.dumps(data), headers=CI_HEADERS) ^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/encoder.py", line 200, in encode chunks = self.iterencode(o, _one_shot=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/encoder.py", line 258, in iterencode return _iterencode(o, 0) ^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/encoder.py", line 180, in default raise TypeError(f'Object of type {o.__class__.__name__} ' ,TypeError: Object of type RemoteException is not JSON serializable
Click this box to copy the error message to your clipboard

😬 Error calling bioimageio-bot, please report the issue to the admin team of bioimage.io: Error: 😬 Failed to reach to the bioimageio-bot, please report the issue to the admin team of bioimage.io: Message: Traceback (most recent call last): , File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 110, in wrapper data = await handler(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 258, in stage return await notify_ci(CI_STAGE_URL, inputs, context=context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 191, in notify_ci resp = requests.post(url, data=json.dumps(data), headers=CI_HEADERS) ^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/encoder.py", line 200, in encode chunks = self.iterencode(o, _one_shot=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/encoder.py", line 258, in iterencode return _iterencode(o, 0) ^^^^^^^^^^^^^^^^^ , File "/home/weiouyang/miniconda3/lib/python3.12/json/encoder.py", line 180, in default raise TypeError(f'Object of type {o.__class__.__name__} ' ,TypeError: Object of type RemoteException is not JSON serializable failed
```

**Comment by oeway** [comment]
> RemoteException

Hi @danifranco Thanks for the report! Forgot that the our s3 server is not ready due to the security restrictions at KTH, I have now updated the upload to support it, please give it a try. I have just uploaded a model and it seems to be working.

**Comment by danifranco** [comment]
Still failing...

![image](https://github.com/user-attachments/assets/1cd18c38-1d40-43dc-883e-9c324763926f)

**Comment by oeway** [comment]
Sorry about that! It looks like our new s3 server at KTH is rejecting your request. I just switched to a different upload proxy, it let me pass the upload:
<img width="759" alt="Screenshot 2024-09-04 at 00 31 59" src="https://github.com/user-attachments/assets/1bfd65d0-4a5e-4f69-8137-35665cedc270">

Could you please try it again, make sure you refresh the page.

**Comment by FynnBe** [comment]
@oeway There is also something going wrong in the CI jobs now:
https://github.com/bioimage-io/collection/actions/runs/10697141414/job/29653719646#step:5:90

```
RuntimeError: failed to open https://hypha.aicell.io/ws-user-github|478667/files/broad-minded-raccoon/model.zip: HTTP Error 403: Forbidden
```
there is a URL in there now that I presume is not truly public?

All 4 staging attempts @oeway ran yesterday and today failed: https://github.com/bioimage-io/collection/actions/workflows/stage.yaml

**Comment by danifranco** [comment]
Now yes the model seems to be uploaded!! Thank you so much!

One quick note: just found an error message when checking the model status. Maybe something more useful for the user should be displayed instead? I mean, something like "The model is being processed . . ." or so.

![image](https://github.com/user-attachments/assets/a009736f-75a7-4884-8d12-8a678230033c)

**Comment by danifranco** [comment]
Also, just saw that the model is not under "Pending uploads" (maybe some first checks must be done before it can appear in that window). However, what I can see is other models pending to be "accepted". Wouldn't it make more sense to display only models submitted by my user? (my opinion)

![image](https://github.com/user-attachments/assets/7041918e-869e-4596-8273-df5c93e3f438)

**Comment by FynnBe** [comment]
sorry this issue fell of my radar... 
the log of adaptable-sauropod show this error:
`failed to open https://hypha.aicell.io/ws-user-github|32868330/files/adaptable-sauropod/model.zip: HTTP Error 403: Forbidden`
Meaning: The uploaded model.zip was not accessible to the collection CI for staging the draft.
I know @oeway has fixed this issue in the meantime, so please reupload the model, if you haven't yet.

**Comment by danifranco** [comment]
OK, just resumitted without errors. It doesn't appear in "Pending uploads" (maybe some time is needed). Here is the model:

![image](https://github.com/user-attachments/assets/76048a63-c23a-4f1c-bfad-3bcf0608dfcb)

**Comment by FynnBe** [comment]
@oeway could you take a look please? There has not been anything triggered in the collection CI... 
https://github.com/bioimage-io/collection/actions/workflows/stage.yaml

**Comment by oeway** [comment]
> @oeway could you take a look please? There has not been anything triggered in the collection CI... https://github.com/bioimage-io/collection/actions/workflows/stage.yaml

I don't see the model uploaded:
<img width="1253" alt="Screenshot 2024-10-21 at 10 14 51" src="https://github.com/user-attachments/assets/d1f9885d-e980-43a8-9e26-2e9039cf1e5e">

Did you click the upload button and see the successfully uploaded message? @danifranco

**Comment by danifranco** [comment]
Yeah, I think I did that... Just tried again and no nickname was automatically specified:

![image](https://github.com/user-attachments/assets/0037c7cc-98fc-416c-a42a-ee1828eed7b6)

I clicked like 20 times the button to "Regenerate nickname" and finally a nickname appeared:

![image](https://github.com/user-attachments/assets/65af5bb0-49d9-4e35-bb55-5f03e4385bb2)

but the error "No nickname specified" is still there. However seems that it was correctly upload now. Checked the link you provided and there is a CI running for that model.

**Comment by oeway** [comment]
Hi @danifranco  sorry about this, I cannot figure out what's the issue related to the nickname. Let's move forward if we can with the current version. Just to be sure, so now the CI passes?

FYI, we are working on a new upload solution to hopefully resolve these issues.

**Comment by FynnBe** [comment]
assuming @oeway  didn't actually trigger [this run of the stage workflow](https://github.com/bioimage-io/collection/actions/runs/11445833695) manually, then the whole upload now worked for the resourceful-ant! 👍 

fyi: the environment specified currently cannot be resolved (pytorch `2.4.0+cu118` + 'cpuonly' (currently required for CI) is not compatible), so I changed it to `2.4.0`... let's see how that goes...

**Comment by cfusterbarcelo** [comment]
Hi @danifranco, @oeway and @FynnBe,
Just to check on the status of this.:Have you managed to solve this? Is there something missing? Has the model been uploaded?

**Comment by FynnBe** [comment]
as reported in a Wednesday meeting, the model has been updated and I fixed the subsequent environment issue for this model.
This revealed the issue that test outputs could not have been regenerated with the described model:
```
| ❌   | `weights.pytorch_state_dict`                                      | Output and expected output disagree:
 
Arrays are not almost equal to 4 decimals

Mismatched elements: 65536 / 65536 (100%)
Max absolute difference: 17.418385
Max relative difference: 2.92232e+08
 x: array([[[[ -9.2528,  -8.0818,  -8.3675, ..., -12.2933, -12.1374,
          -10.9521],
         [-10.0423,  -9.2579,  -9.6984, ..., -13.8429, -13.4351,...
 y: array([[[[5.3883e-05, 9.4593e-05, 8.7500e-05, ..., 2.9802e-07,
          2.3842e-07, 4.7684e-07],
         [3.5107e-05, 8.0287e-05, 8.4817e-05, ..., 2.3842e-07,... |
         
```

As I mentioned, @danifranco is on vacation at the moment (or maybe juuust came back..?)... However, he knows what to do to improve the model and make it pass.
I changed the status to 'requested changes' so this is marked at https://bioimageio-uploader.netlify.app/#/status/resourceful-ant

**Comment by danifranco** [comment]
Yeah, I'm back. Will take a look asap to this and get back to you!
