### ISSUE TITLE
Fail to download `pytorch_state_dict` if other formats exist

### ISSUE THREAD

**Issue by qin-yu** [bioimage-io/archive.bioimage.io#419]
In the `philosophical-panda` model, the state dict download button does not trigger a file download, while the torchscript download button works as expected. This issue is not present in another model that only has a state dict option. However, in a similar model with multiple download options, like `affable-shark`, a similar problem occurs.

I suspect that this is a bug instead of an internet problem, because there was a similar problem before: https://github.com/bioimage-io/core-bioimage-io-python/issues/396

Figures: downloading file takes forever for these models.

![image](https://github.com/user-attachments/assets/e1a97468-d80f-4374-a541-f4892f0ce619)
![image](https://github.com/user-attachments/assets/5a9399f7-64e7-4e66-85db-621558dbcc8f)

**Comment by cfusterbarcelo** [comment]
Hi @qin-yu,

I tried reproducing the issue by downloading the `philosophical-panda` model. While it does take some time to download, I was able to complete the download successfully.
![image](https://github.com/user-attachments/assets/40b48055-aff2-4707-b985-34df42f446fc)

I’m aware of the previous issues with the `affable-shark` model mentioned in [this issue](https://github.com/bioimage-io/bioimage.io/issues/434), but I attempted to reproduce the problem, and it seems to be working fine now. Could you please try again and let us know if the issue persists?

Looking forward to your update!

**Comment by IvanHCenalmor** [comment]
I was getting the issue on `affable-shark`, but seemed to be an issue with the network configuration of the institute. So as you point it might be an issue with the internet connection.

As another use case, I tried downloading `philosophical-panda` and for me it also works the downloading from both `Torchscript` and `Pytorch State Dict`:
![Screenshot 2024-12-03 at 17 36 05](https://github.com/user-attachments/assets/5648efd0-d705-409f-9828-93fda9139faf)

**Comment by cfusterbarcelo** [comment]
Thank you for your testing @IvanHCenalmor!
@qin-yu Could you test it again to see if this is working now?
Thank you!

**Comment by qin-yu** [comment]
> @qin-yu Could you test it again to see if this is working now? Thank you!

It's working now @cfusterbarcelo 

> I was getting the issue on `affable-shark`, but seemed to be an issue with the network configuration of the institute. So as you point it might be an issue with the internet connection.

I don't believe the network configuration can affect only one format not the other @IvanHCenalmor. My original issue was describing that, for two models that have torchscript, state dict cannot be downloaded while torchscript can. Different weights for the same model have been stored next to each other in the same folder.
