### ISSUE TITLE
Failed to Download pytorch State Dict from website

### ISSUE THREAD

**Issue by Josh-Talks** [bioimage-io/archive.bioimage.io#423]
I was trying to download the pytorch state dict for the powerful chipmunk-model https://bioimage.io/#/?id=10.5281%2Fzenodo.5847355 in order to run it on ilastik. clicking on the ilastik logo and then clicking the download pytorch state dict button doesn't work and gives the following error in the console.
<img width="723" alt="image" src="https://github.com/user-attachments/assets/7a4e21f1-56a3-4b74-83d8-91c3445bffb5">

**Comment by cfusterbarcelo** [comment]
Hello Josh, 
Thanks for telling us! There is in fact an error with the button on downloading weights for Ilastik. We are taking care of it and will tell you as soon as this is solved. 

Thank you!
Best, 
Caterina

**Comment by cfusterbarcelo** [comment]
Hi again Josh, 
This is now solved! Try it again and tell us if you have any other issue!

Thank you for pointing it out!
Best, 
Caterina
