### ISSUE TITLE
Documentation links not found

### ISSUE THREAD

**Issue by ElpadoCan** [bioimage-io/archive.bioimage.io#425]
The documentation links referenced [here](https://github.com/bioimage-io/bioimage.io/blob/7d8a8b3686b4aaef56a4688635557b2824281149/docs/guides/community-partners-guide.md?plain=1#L171) do not exist. 

Specifically, they point to the file `/contribute_models/README.md` and `/community_partners/README.md` and these files do not seem to exist.

**Comment by cfusterbarcelo** [comment]
Hi there,

Thank you for bringing this to our attention! The link issues have been resolved.

As you were reviewing the documentation on becoming a community partner, I'd like to let you know that the process has recently been updated. You can now apply through our new procedure.

If you have any questions, feel free to reach out! You can either fill out the [TypeForm](https://oeway.typeform.com/to/K3j2tJt7?typeform-source=bioimage.io) or email us directly at ai4lifesupport@eurobioimaging.eu.

Best, 
Caterina

**Comment by ElpadoCan** [comment]
Hi Caterina,

Thank you very much for the information and the very quick fix. 

I have a small question, I saw that @FynnBe moved my request to become a community partner from the [bioimage-io/collection-bioimage-io](https://github.com/bioimage-io/collection-bioimage-io/issues) repo to the [bioimage-io/collection](https://github.com/bioimage-io/collection). 

Should the documentation also point to the newer [bioimage-io/collection](https://github.com/bioimage-io/collection) page for the community partners requests?

**Comment by FynnBe** [comment]
> Should the documentation also point to the newer [bioimage-io/collection](https://github.com/bioimage-io/collection) page for the community partners requests?

yes

**Comment by ElpadoCan** [comment]
> > Should the documentation also point to the newer [bioimage-io/collection](https://github.com/bioimage-io/collection) page for the community partners requests?
> 
> yes

Great, I just created PR #428 to fix that.
