### ISSUE TITLE
Add a page with a small description about comminuty partners

### ISSUE THREAD

**Issue by ElpadoCan** [bioimage-io/archive.bioimage.io#432]
Currently, clicking on the community partners logos filters the results right? However, there isn't a way to get more information about who the partners are (unless I missed it). 

It would be nice to have a dedicated page with a small description of each community partner and a link to their home pages. 

I’m not familiar with JavaScript and Vue otherwise I would make it myself and create a PR. Thanks!

**Comment by esgomezm** [comment]
Hi @ElpadoCan 
Yes, there is. As a community partner you can have a dedicated card, like this one for DL4MicEverywhere (https://bioimage.io/#/?type=application&tags=dl4miceverywhere&id=dl4miceverywhere%2Fdl4miceverywhere).  
For this, you need to add in your repository the resource description as an application (https://github.com/HenriquesLab/DL4MicEverywhere-bioimage-io/blob/10b87fa1d8a380b14cfb444f4b2b71f22a515595/collection.yaml#L163). You will see the same for other partners such as deepImageJ, Ilastik, biapy or ZeroCostDL4Mic. In this card, you could add links to your doc or any other description.
Additionally, in the documentation, it is also possible to add further information (https://bioimage.io/docs/#/guides/user-guide?id=using-bioimage-model-zoo-models-in-different-software).

**Comment by ElpadoCan** [comment]
Hi @esgomezm, 

Fantastic that is exactly what I was looking for, I will definitely do it for my repo. However, I don't understand how are these cards accessed from the website? With my 30 seconds of clicking around I could not re-open the one you linked for DL4MicEverywhere 😄. Thank you for your patience!

**Comment by ElpadoCan** [comment]
Ok, I got it now, I can get to that card once I click on a resource contributed by that partner. Thank you for the info! 

In the longer term, would it be possible to collect these cards info on a dedicated page? Not a priority, just a small suggestion. Thanks again!

**Comment by cfusterbarcelo** [comment]
Hi @ElpadoCan! 
There’s a section in the documentation specifically for Community Partners, which you can find [here](https://bioimage.io/docs/#/guides/community-partners-guide?id=meet-our-community-partners). However, please note that this information is currently outdated because the file that provides this data has been moved, and I haven’t had the chance to update the link yet. I’ll make sure to address this as soon as possible, but just so you’re aware, the section does exist. 
Thanks for your understanding!
