### ISSUE TITLE
Failed to download `affabable-shark` weights

### ISSUE THREAD

**Issue by IvanHCenalmor** [bioimage-io/archive.bioimage.io#434]
When trying to download the weights from `affabable-shark` is giving me the following error:

![Screenshot from 2024-11-27 11-53-37](https://github.com/user-attachments/assets/bb43de41-3fd6-445f-b788-a05ab0ba5400)

The model is downloaded, but the weights are not there:

![image](https://github.com/user-attachments/assets/82bf567d-f11e-47c2-9e9a-8848b152a3cc)

**Comment by BiologyTools** [comment]
Seems to work now! 
![image](https://github.com/user-attachments/assets/72315120-2a0f-4923-acd0-276fff333fad)

**Comment by cfusterbarcelo** [comment]
Hi @IvanHCenalmor, could you please test it again? I just checked on my end, and it seems to be working. I downloaded the `affable-shark` weights in TorchScript format, and everything loaded successfully. Let me know if you're encountering a specific error or if there's a step I can help clarify.

<img width="202" alt="image" src="https://github.com/user-attachments/assets/86e0e38f-2b3d-4851-b8f9-719c9db2f100">

Please tell me or close the issue if solved! Thanks!

**Comment by IvanHCenalmor** [comment]
Hi @cfusterbarcelo,

I’ve tested it again on the same computer, and unfortunately, it still doesn’t work. I’m not 100% sure where the issue lies, but it seems to be related to the internal network settings of the institute or possibly a download request issue specific to this computer.

That said, I’ve tested it on other computers, and it works perfectly for me there!

So, it’s not really an issue with the model itself but rather with my computer. I’ll go ahead and close the issue since everything works as expected. 🤗

Thanks!
