### ISSUE TITLE
Contribution field on website is too complicated

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#54]
The description is very complicated and technical; for example the term RDF is confusing.

We should have an easier and more concise description:
- Provide a link to the example yaml and to the specification
- Provide a link to a tutorial + to more examples

In general, need more examples.

cc @akreshuk @vzinche

**Comment by vzinche** [comment]
I would generally just write something like:

If you want to contribute a:
* model - follow [Model Tutorial](some_link1)
* notebook - follow [Notebook Tutorial](some_link2) 
* application - follow [Application Tutorial](some_link3)

**Comment by oeway** [comment]
Good idea, thanks!

Contributions for improving this are welcome, I didn't have time to improve it, but only provide a rough and technical document with all the possibilities. Feel free to modify [this file](https://github.com/bioimage-io/bioimage.io/blob/master/docs/contribute.md) directly, and it will be rendered to the website.


Regarding the term "RDF", it's a generalised version that derived from the model description file, aims to cover all types of resources that are relevant to AI models. I think we should widen the scope a bit to get closer to the website name "BioImage.IO": Input and Outputs for bioimaging. Again, this does not mean RDF is a term I would like to stick with, suggestions for this is also welcome. Basically, we would like to have a set of basic fields shared for all types of resource items, and then specific fields for models, datasets, notebooks, applications, etc.
