### ISSUE TITLE
Meta-issue: Website design

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#58]
We had a discussion on the design / layout of the bioimage.io website with @vzinche @m-novikov and @akreshuk today.
Most of this was based on feedback @vzinche got from running a ZIDAS image analysis course and getting feedback from the course participants.
See Issues bioimage-io/archive.bioimage.io#57 bioimage-io/archive.bioimage.io#54 bioimage-io/archive.bioimage.io#55 bioimage-io/archive.bioimage.io#56 for detailed issues.

Two more observations:
- Clicking the "Community Partner" icons doesn't work properly, e.g. models are not listed for ilastik and fiji
- The message displayed when clicking "Share" is not very helpful; it should at least have the url in the message, and at some point should even link to twitter etc. 

It's probably a good idea to set discussion of this on the agenda for the call on Friday, see bioimage-io/bioimage.io#3.
Unfortunately I can't make it, but @akreshuk will be there from our side.

**Comment by oeway** [comment]
Thanks for these suggestions, I tried to explain for some of them.

For the community partner issue, I just investigate a bit, it's basically because non of the ilastik/fiji model has the `ilastik` or `fiji` tag applied. Those buttons works by applying a tag filter when you click, so please make sure you explicitly set a ilastik tag for ilastik models.

The share button has been improved in https://github.com/bioimage-io/bioimage.io/pull/59 , a preview version here: https://deploy-preview-59--bioimage.netlify.app/

Sounds good, thanks for all these, we can discuss them over the meeting.

**Comment by constantinpape** [comment]
> For the community partner issue, I just investigate a bit, it's basically because non of the ilastik/fiji model has the `ilastik` or `fiji` tag applied. Those buttons works by applying a tag filter when you click, so please make sure you explicitly set a ilastik tag for ilastik models.

Ok, thanks. We can fix it for the ilastik models.

> The share button has been improved in bioimage-io/archive.bioimage.io#59 , a preview version here: https://deploy-preview-59--bioimage.netlify.app/

Looks good. (I think eventually we would want "Copy to clipboard" and "Share via twitter", but for now this is totally fine!)

**Comment by oeway** [comment]
> Looks good. (I think eventually we would want "Copy to clipboard" and "Share via twitter", but for now this is totally fine!)

Sure, we will have those social buttons one day ;)

> Ok, thanks. We can fix it for the ilastik models.

BTW,  @constantinpape I think it's better for you(Ilastik) to host your own `manifest.bioimage.io.yaml` file under one of your ilastik/tiktorch repo. Like that you can manage you own repo, no need to send PR to the central model repo when you want to add models. See the [deepImageJ example](https://github.com/deepimagej/models/blob/master/manifest.bioimage.io.yaml), and [this](https://github.com/bioimage-io/bioimage-io-models/blob/e45d95c95e731b728900949d1e15b536d8562ed2/src/manifest.bioimage.io.yaml#L27-L28) is how we connect it to the central model zoo as a collection.  Meanwhile, you can also add or adopt [this CI file](https://github.com/deepimagej/models/blob/master/.github/workflows/compile-manifest.yml) for run tests in your repo when you add new models.

If you do that, the latest compilation script will apply the ilastik tag automatically for all the models in your repo.
