### ISSUE TITLE
Animate list of covers

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#6]
I was expecting the list of covers to be shown like a slide show, but at the moment only the first cover image is shown for " 3D UNet Platynereis Cell Segmentation (Probabilities)"[name is also too long atm]
This is particularly unfortunate, as the first one shows only raw data.
![image](https://user-images.githubusercontent.com/15139589/75691780-cfdd4c00-5ca4-11ea-81c4-b040964b9397.png)

For "3D UNet Arabidopsis Ovules" this is the case on the preview windows, but there is another problem: the card does not show any cover image at all.
![image](https://user-images.githubusercontent.com/15139589/75691815-dbc90e00-5ca4-11ea-949a-da22113db6f3.png)
![image](https://user-images.githubusercontent.com/15139589/75691692-b2a87d80-5ca4-11ea-8b7a-34a02ca98a50.png)

**Comment by oeway** [comment]
Hi @FynnBe I haven't had time to implement that yet, for you, only the first one is shown.

For the other issue, I just checked, the problem caused by the brackets in the file name, could you please change the file name and remove the brackets? say, change `ilastik(4).png` to `ilastik-4.png`?
