### ISSUE TITLE
Support permalinks for applications

### ISSUE THREAD

**Issue by m-novikov** [bioimage-io/archive.bioimage.io#79]
Accessing link of this format https://bioimage.io/#/?tags=Ilastik
I would expect to get prefiltered results for `ilastik` tag
But once the site is loaded it discards tags provided in the link.

**Comment by m-novikov** [comment]
The following link format works: https://bioimage.io/#/?partner=ilastik&type=model

**Comment by oeway** [comment]
Thanks for the report! Will look into it.
